use chrono::prelude::*;
use chrono::{DateTime, Duration};
use chrono_tz::Tz;
use std::cmp::Ordering;

/// Create a Vector of time increments in the future from now for the given `timezone`.
pub fn new_future_increments(current_future_increments: i32, timezone: &Tz) -> Vec<TimeIncrement> {
    let mut new_increments = vec![TimeIncrement::now(timezone.clone())];

    for _ in 1..current_future_increments {
        let mut new_hour = new_increments.last().unwrap().clone();
        new_hour.add(Duration::hours(1));
        new_hour.now = false;
        new_increments.push(new_hour);
    }

    // remove now
    new_increments.remove(0);

    new_increments
}

/// Create a Vector of time increments in the past from now for the given `timezone`.
pub fn new_past_increments(current_future_increments: i32, timezone: &Tz) -> Vec<TimeIncrement> {
    let mut new_increments = vec![TimeIncrement::now(timezone.clone())];

    for _ in 1..current_future_increments {
        let mut new_hour = new_increments.first().unwrap().clone();
        new_hour.minus(Duration::hours(1));
        new_hour.now = false;
        new_increments.insert(0, new_hour);
    }

    // remove now
    let _ = new_increments.pop();

    new_increments
}

#[derive(Debug, Clone, Copy)]
pub struct TimeIncrement {
    pub timezone: Tz,
    pub datetime: DateTime<Tz>,
    pub now: bool,
}

impl TimeIncrement {
    pub fn now(timezone: Tz) -> Self {
        let datetime = Utc::now().with_timezone(&timezone);

        Self {
            datetime,
            timezone,
            now: true,
        }
    }

    pub fn new(timezone: Tz, new_hour: u32) -> Self {
        let datetime = Utc::now()
            .with_timezone(&timezone)
            .with_hour(new_hour)
            .unwrap();

        Self {
            datetime,
            timezone,
            now: false,
        }
    }

    pub fn from_timestamp(timestamp: i64, timezone: Tz) -> Self {
        if let Some(datetime) = DateTime::from_timestamp(timestamp, 0) {
            Self {
                datetime: datetime.with_timezone(&timezone),
                timezone,
                now: false,
            }
        } else {
            Self::now(timezone)
        }
    }

    pub fn get_hour(&self) -> u32 {
        self.datetime.hour()
    }

    pub fn add(&mut self, duration: Duration) {
        self.datetime = self.datetime + duration;
    }

    pub fn minus(&mut self, duration: Duration) {
        self.datetime = self.datetime - duration;
    }

    /// Print an emoji, city name and timezone code to inform the user
    /// which timezone they are looking at.
    pub fn display_header(&self) -> String {
        let time = self.datetime;
        format!(
            "{} {} ({})",
            tz_to_emoji(&self.timezone),
            tz_to_city(&self.timezone),
            time.format("%Z").to_string(),
        )
    }

    /// Print the time rounded to the nearest increment. Most timezones
    /// round to a whole hour but some like India and Nepal round to
    /// half and quarter hours.
    pub fn display_time_rounded(&self) -> String {
        // Change the datetime back to the UTC timezone, remove the minutes
        // and then add the timezone back on to add the timezone hour and
        // minute increments.
        let rounded_datetime = self
            .datetime
            .to_utc()
            .with_minute(0)
            .unwrap_or_default()
            .with_timezone(&self.timezone);

        rounded_datetime.format("%H:%M").to_string()
    }

    /// Print the time.
    pub fn display_time(&self) -> String {
        // Change the datetime back to the UTC timezone, remove the minutes
        // and then add the timezone back on to add the timezone hour and
        // minute increments.
        let rounded_datetime = self.datetime.to_utc().with_timezone(&self.timezone);

        rounded_datetime.format("%H:%M").to_string()
    }

    /// Print the day of the time displayed in the [display_time] method.
    pub fn display_date(&self) -> String {
        self.datetime.format("%e %B %Y").to_string()
    }

    /// Return the number of seconds since January 1, 1970 0:00:00 UTC (aka “UNIX timestamp”)
    pub fn timestamp(&self) -> i64 {
        self.datetime.to_utc().timestamp()
    }

    /// The date in the format required for the html date input
    pub fn input_date(&self) -> String {
        self.datetime.format("%Y-%m-%d").to_string()
    }

    /// The time in the format required for the html time input
    /// rounded to the nearest hour.
    pub fn input_time_rounded(&self) -> String {
        self.datetime.format("%H:00").to_string()
    }

    /// The time in the format required for the html time input
    pub fn input_time(&self) -> String {
        self.datetime.format("%H:%M").to_string()
    }
}

/// Allow for vectors of timezones to be sorted by their Offset i.e.
/// the UTC+01:00 part of a timestamp.
impl Ord for TimeIncrement {
    fn cmp(&self, other: &Self) -> Ordering {
        let self_offset = self
            .datetime
            .format("%z")
            .to_string()
            .parse::<u32>()
            .unwrap();
        let other_offset = other
            .datetime
            .format("%z")
            .to_string()
            .parse::<u32>()
            .unwrap();

        self_offset.cmp(&other_offset)
    }
}

impl PartialOrd for TimeIncrement {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl PartialEq for TimeIncrement {
    fn eq(&self, other: &Self) -> bool {
        self.timezone == other.timezone
    }
}

impl Eq for TimeIncrement {}

/// Returns a tuple of the timezone displayable components as this: (emoji, city, country)
pub fn tz_display(timezone: &Tz) -> (String, String, String) {
    (
        tz_to_emoji(timezone),
        tz_to_city(timezone),
        tz_to_country(timezone),
    )
}

pub fn tz_to_city(timezone: &Tz) -> String {
    match timezone {
        Tz::Africa__Abidjan => "Abidjan",
        Tz::Africa__Accra => "Accra",
        Tz::Africa__Addis_Ababa => "Addis Ababa",
        Tz::Africa__Algiers => "Algiers",
        Tz::Africa__Asmara => "Asmara",
        Tz::Africa__Asmera => "Asmera",
        Tz::Africa__Bamako => "Bamako",
        Tz::Africa__Bangui => "Bangui",
        Tz::Africa__Banjul => "Banjul",
        Tz::Africa__Bissau => "Bissau",
        Tz::Africa__Blantyre => "Blantyre",
        Tz::Africa__Brazzaville => "Brazzaville",
        Tz::Africa__Bujumbura => "Bujumbura",
        Tz::Africa__Cairo => "Cairo",
        Tz::Africa__Casablanca => "Casablanca",
        Tz::Africa__Ceuta => "Ceuta",
        Tz::Africa__Conakry => "Conakry",
        Tz::Africa__Dakar => "Dakar",
        Tz::Africa__Dar_es_Salaam => "Dar es Salaam",
        Tz::Africa__Djibouti => "Djibouti",
        Tz::Africa__Douala => "Douala",
        Tz::Africa__El_Aaiun => "El Aaiun",
        Tz::Africa__Freetown => "Freetown",
        Tz::Africa__Gaborone => "Gaborone",
        Tz::Africa__Harare => "Harare",
        Tz::Africa__Johannesburg => "Johannesburg",
        Tz::Africa__Juba => "Juba",
        Tz::Africa__Kampala => "Kampala",
        Tz::Africa__Khartoum => "Khartoum",
        Tz::Africa__Kigali => "Kigali",
        Tz::Africa__Kinshasa => "Kinshasa",
        Tz::Africa__Lagos => "Lagos",
        Tz::Africa__Libreville => "Libreville",
        Tz::Africa__Lome => "Lome",
        Tz::Africa__Luanda => "Luanda",
        Tz::Africa__Lubumbashi => "Lubumbashi",
        Tz::Africa__Lusaka => "Lusaka",
        Tz::Africa__Malabo => "Malabo",
        Tz::Africa__Maputo => "Maputo",
        Tz::Africa__Maseru => "Maseru",
        Tz::Africa__Mbabane => "Mbabane",
        Tz::Africa__Mogadishu => "Mogadishu",
        Tz::Africa__Monrovia => "Monrovia",
        Tz::Africa__Nairobi => "Nairobi",
        Tz::Africa__Ndjamena => "Ndjamena",
        Tz::Africa__Niamey => "Niamey",
        Tz::Africa__Nouakchott => "Nouakchott",
        Tz::Africa__Ouagadougou => "Ouagadougou",
        Tz::Africa__PortoNovo => "Porto-Novo",
        Tz::Africa__Sao_Tome => "Sao_Tome",
        Tz::Africa__Timbuktu => "Timbuktu",
        Tz::Africa__Tripoli => "Tripoli",
        Tz::Africa__Tunis => "Tunis",
        Tz::Africa__Windhoek => "Windhoek",
        Tz::America__Adak => "Adak",
        Tz::America__Anchorage => "Anchorage",
        Tz::America__Anguilla => "Anguilla",
        Tz::America__Antigua => "Antigua",
        Tz::America__Araguaina => "Araguaina",
        Tz::America__Argentina__Buenos_Aires => "Argentina Buenos Aires",
        Tz::America__Argentina__Catamarca => "Argentina Catamarca",
        Tz::America__Argentina__ComodRivadavia => "Argentina Comod Rivadavia",
        Tz::America__Argentina__Cordoba => "Argentina Cordoba",
        Tz::America__Argentina__Jujuy => "Argentina Jujuy",
        Tz::America__Argentina__La_Rioja => "Argentina La_Rioja",
        Tz::America__Argentina__Mendoza => "Argentina Mendoza",
        Tz::America__Argentina__Rio_Gallegos => "Argentina Rio Gallegos",
        Tz::America__Argentina__Salta => "Argentina Salta",
        Tz::America__Argentina__San_Juan => "Argentina San Juan",
        Tz::America__Argentina__San_Luis => "Argentina San Luis",
        Tz::America__Argentina__Tucuman => "Argentina Tucuman",
        Tz::America__Argentina__Ushuaia => "Argentina Ushuaia",
        Tz::America__Aruba => "Aruba",
        Tz::America__Asuncion => "Asuncion",
        Tz::America__Atikokan => "Atikokan",
        Tz::America__Atka => "Atka",
        Tz::America__Bahia => "Bahia",
        Tz::America__Bahia_Banderas => "Bahia_Banderas",
        Tz::America__Barbados => "Barbados",
        Tz::America__Belem => "Belem",
        Tz::America__Belize => "Belize",
        Tz::America__BlancSablon => "Blanc-Sablon",
        Tz::America__Boa_Vista => "Boa_Vista",
        Tz::America__Bogota => "Bogota",
        Tz::America__Boise => "Boise",
        Tz::America__Buenos_Aires => "Buenos Aires",
        Tz::America__Cambridge_Bay => "Cambridge Bay",
        Tz::America__Campo_Grande => "Campo Grande",
        Tz::America__Cancun => "Cancun",
        Tz::America__Caracas => "Caracas",
        Tz::America__Catamarca => "Catamarca",
        Tz::America__Cayenne => "Cayenne",
        Tz::America__Cayman => "Cayman",
        Tz::America__Chicago => "Chicago",
        Tz::America__Chihuahua => "Chihuahua",
        Tz::America__Ciudad_Juarez => "Ciudad Juarez",
        Tz::America__Coral_Harbour => "Coral Harbour",
        Tz::America__Cordoba => "Cordoba",
        Tz::America__Costa_Rica => "Costa Rica",
        Tz::America__Coyhaique => "Coyhaique",
        Tz::America__Creston => "Creston",
        Tz::America__Cuiaba => "Cuiaba",
        Tz::America__Curacao => "Curacao",
        Tz::America__Danmarkshavn => "Danmarkshavn",
        Tz::America__Dawson => "Dawson",
        Tz::America__Dawson_Creek => "Dawson Creek",
        Tz::America__Denver => "Denver",
        Tz::America__Detroit => "Detroit",
        Tz::America__Dominica => "Dominica",
        Tz::America__Edmonton => "Edmonton",
        Tz::America__Eirunepe => "Eirunepe",
        Tz::America__El_Salvador => "El Salvador",
        Tz::America__Ensenada => "Ensenada",
        Tz::America__Fort_Nelson => "Fort Nelson",
        Tz::America__Fort_Wayne => "Fort Wayne",
        Tz::America__Fortaleza => "Fortaleza",
        Tz::America__Glace_Bay => "Glace Bay",
        Tz::America__Godthab => "Godthab",
        Tz::America__Goose_Bay => "Goose Bay",
        Tz::America__Grand_Turk => "Grand Turk",
        Tz::America__Grenada => "Grenada",
        Tz::America__Guadeloupe => "Guadeloupe",
        Tz::America__Guatemala => "Guatemala",
        Tz::America__Guayaquil => "Guayaquil",
        Tz::America__Guyana => "Guyana",
        Tz::America__Halifax => "Halifax",
        Tz::America__Havana => "Havana",
        Tz::America__Hermosillo => "Hermosillo",
        Tz::America__Indiana__Indianapolis => "Indianapolis",
        Tz::America__Indiana__Knox => "Knox",
        Tz::America__Indiana__Marengo => "Marengo",
        Tz::America__Indiana__Petersburg => "Petersburg",
        Tz::America__Indiana__Tell_City => "Tell City",
        Tz::America__Indiana__Vevay => "Vevay",
        Tz::America__Indiana__Vincennes => "Vincennes",
        Tz::America__Indiana__Winamac => "Winamac",
        Tz::America__Indianapolis => "Indianapolis",
        Tz::America__Inuvik => "Inuvik",
        Tz::America__Iqaluit => "Iqaluit",
        Tz::America__Jamaica => "Jamaica",
        Tz::America__Jujuy => "Jujuy",
        Tz::America__Juneau => "Juneau",
        Tz::America__Kentucky__Louisville => "Louisville",
        Tz::America__Kentucky__Monticello => "Monticello",
        Tz::America__Knox_IN => "Knox IN",
        Tz::America__Kralendijk => "Kralendijk",
        Tz::America__La_Paz => "La Paz",
        Tz::America__Lima => "Lima",
        Tz::America__Los_Angeles => "Los_Angeles",
        Tz::America__Louisville => "Louisville",
        Tz::America__Lower_Princes => "Lower Princes",
        Tz::America__Maceio => "Maceio",
        Tz::America__Managua => "Managua",
        Tz::America__Manaus => "Manaus",
        Tz::America__Marigot => "Marigot",
        Tz::America__Martinique => "Martinique",
        Tz::America__Matamoros => "Matamoros",
        Tz::America__Mazatlan => "Mazatlan",
        Tz::America__Mendoza => "Mendoza",
        Tz::America__Menominee => "Menominee",
        Tz::America__Merida => "Merida",
        Tz::America__Metlakatla => "Metlakatla",
        Tz::America__Mexico_City => "Mexico City",
        Tz::America__Miquelon => "Miquelon",
        Tz::America__Moncton => "Moncton",
        Tz::America__Monterrey => "Monterrey",
        Tz::America__Montevideo => "Montevideo",
        Tz::America__Montreal => "Montreal",
        Tz::America__Montserrat => "Montserrat",
        Tz::America__Nassau => "Nassau",
        Tz::America__New_York => "New York",
        Tz::America__Nipigon => "Nipigon",
        Tz::America__Nome => "Nome",
        Tz::America__Noronha => "Noronha",
        Tz::America__North_Dakota__Beulah => "Beulah",
        Tz::America__North_Dakota__Center => "Center",
        Tz::America__North_Dakota__New_Salem => "New Salem",
        Tz::America__Nuuk => "Nuuk",
        Tz::America__Ojinaga => "Ojinaga",
        Tz::America__Panama => "Panama",
        Tz::America__Pangnirtung => "Pangnirtung",
        Tz::America__Paramaribo => "Paramaribo",
        Tz::America__Phoenix => "Phoenix",
        Tz::America__PortauPrince => "Port-au-Prince",
        Tz::America__Port_of_Spain => "Port of Spain",
        Tz::America__Porto_Acre => "Porto Acre",
        Tz::America__Porto_Velho => "Porto Velho",
        Tz::America__Puerto_Rico => "Puerto Rico",
        Tz::America__Punta_Arenas => "Punta Arenas",
        Tz::America__Rainy_River => "Rainy River",
        Tz::America__Rankin_Inlet => "Rankin Inlet",
        Tz::America__Recife => "Recife",
        Tz::America__Regina => "Regina",
        Tz::America__Resolute => "Resolute",
        Tz::America__Rio_Branco => "Rio Branco",
        Tz::America__Rosario => "Rosario",
        Tz::America__Santa_Isabel => "Santa Isabel",
        Tz::America__Santarem => "Santarem",
        Tz::America__Santiago => "Santiago",
        Tz::America__Santo_Domingo => "Santo Domingo",
        Tz::America__Sao_Paulo => "Sao_Paulo",
        Tz::America__Scoresbysund => "Scoresbysund",
        Tz::America__Shiprock => "Shiprock",
        Tz::America__Sitka => "Sitka",
        Tz::America__St_Barthelemy => "St Barthelemy",
        Tz::America__St_Johns => "St Johns",
        Tz::America__St_Kitts => "St Kitts",
        Tz::America__St_Lucia => "St Lucia",
        Tz::America__St_Thomas => "St Thomas",
        Tz::America__St_Vincent => "St Vincent",
        Tz::America__Swift_Current => "Swift Current",
        Tz::America__Tegucigalpa => "Tegucigalpa",
        Tz::America__Thule => "Thule",
        Tz::America__Thunder_Bay => "Thunder Bay",
        Tz::America__Tijuana => "Tijuana",
        Tz::America__Toronto => "Toronto",
        Tz::America__Tortola => "Tortola",
        Tz::America__Vancouver => "Vancouver",
        Tz::America__Virgin => "Virgin",
        Tz::America__Whitehorse => "Whitehorse",
        Tz::America__Winnipeg => "Winnipeg",
        Tz::America__Yakutat => "Yakutat",
        Tz::America__Yellowknife => "Yellowknife",
        Tz::Antarctica__Casey => "Casey",
        Tz::Antarctica__Davis => "Davis",
        Tz::Antarctica__DumontDUrville => "Dumont D'Urville",
        Tz::Antarctica__Macquarie => "Macquarie",
        Tz::Antarctica__Mawson => "Mawson",
        Tz::Antarctica__McMurdo => "McMurdo",
        Tz::Antarctica__Palmer => "Palmer",
        Tz::Antarctica__Rothera => "Rothera",
        Tz::Antarctica__South_Pole => "South Pole",
        Tz::Antarctica__Syowa => "Syowa",
        Tz::Antarctica__Troll => "Troll",
        Tz::Antarctica__Vostok => "Vostok",
        Tz::Arctic__Longyearbyen => "Longyearbyen",
        Tz::Asia__Aden => "Aden",
        Tz::Asia__Almaty => "Almaty",
        Tz::Asia__Amman => "Amman",
        Tz::Asia__Anadyr => "Anadyr",
        Tz::Asia__Aqtau => "Aqtau",
        Tz::Asia__Aqtobe => "Aqtobe",
        Tz::Asia__Ashgabat => "Ashgabat",
        Tz::Asia__Ashkhabad => "Ashkhabad",
        Tz::Asia__Atyrau => "Atyrau",
        Tz::Asia__Baghdad => "Baghdad",
        Tz::Asia__Bahrain => "Bahrain",
        Tz::Asia__Baku => "Baku",
        Tz::Asia__Bangkok => "Bangkok",
        Tz::Asia__Barnaul => "Barnaul",
        Tz::Asia__Beirut => "Beirut",
        Tz::Asia__Bishkek => "Bishkek",
        Tz::Asia__Brunei => "Brunei",
        Tz::Asia__Calcutta => "Calcutta",
        Tz::Asia__Chita => "Chita",
        Tz::Asia__Choibalsan => "Choibalsan",
        Tz::Asia__Chongqing => "Chongqing",
        Tz::Asia__Chungking => "Chungking",
        Tz::Asia__Colombo => "Colombo",
        Tz::Asia__Dacca => "Dacca",
        Tz::Asia__Damascus => "Damascus",
        Tz::Asia__Dhaka => "Dhaka",
        Tz::Asia__Dili => "Dili",
        Tz::Asia__Dubai => "Dubai",
        Tz::Asia__Dushanbe => "Dushanbe",
        Tz::Asia__Famagusta => "Famagusta",
        Tz::Asia__Gaza => "Gaza",
        Tz::Asia__Harbin => "Harbin",
        Tz::Asia__Hebron => "Hebron",
        Tz::Asia__Ho_Chi_Minh => "Ho Chi Minh",
        Tz::Asia__Hong_Kong => "Hong Kong",
        Tz::Asia__Hovd => "Hovd",
        Tz::Asia__Irkutsk => "Irkutsk",
        Tz::Asia__Istanbul => "Istanbul",
        Tz::Asia__Jakarta => "Jakarta",
        Tz::Asia__Jayapura => "Jayapura",
        Tz::Asia__Jerusalem => "Jerusalem",
        Tz::Asia__Kabul => "Kabul",
        Tz::Asia__Kamchatka => "Kamchatka",
        Tz::Asia__Karachi => "Karachi",
        Tz::Asia__Kashgar => "Kashgar",
        Tz::Asia__Kathmandu => "Kathmandu",
        Tz::Asia__Katmandu => "Katmandu",
        Tz::Asia__Khandyga => "Khandyga",
        Tz::Asia__Kolkata => "Kolkata",
        Tz::Asia__Krasnoyarsk => "Krasnoyarsk",
        Tz::Asia__Kuala_Lumpur => "Kuala Lumpur",
        Tz::Asia__Kuching => "Kuching",
        Tz::Asia__Kuwait => "Kuwait",
        Tz::Asia__Macao => "Macao",
        Tz::Asia__Macau => "Macau",
        Tz::Asia__Magadan => "Magadan",
        Tz::Asia__Makassar => "Makassar",
        Tz::Asia__Manila => "Manila",
        Tz::Asia__Muscat => "Muscat",
        Tz::Asia__Nicosia => "Nicosia",
        Tz::Asia__Novokuznetsk => "Novokuznetsk",
        Tz::Asia__Novosibirsk => "Novosibirsk",
        Tz::Asia__Omsk => "Omsk",
        Tz::Asia__Oral => "Oral",
        Tz::Asia__Phnom_Penh => "Phnom Penh",
        Tz::Asia__Pontianak => "Pontianak",
        Tz::Asia__Pyongyang => "Pyongyang",
        Tz::Asia__Qatar => "Qatar",
        Tz::Asia__Qostanay => "Qostanay",
        Tz::Asia__Qyzylorda => "Qyzylorda",
        Tz::Asia__Rangoon => "Rangoon",
        Tz::Asia__Riyadh => "Riyadh",
        Tz::Asia__Saigon => "Saigon",
        Tz::Asia__Sakhalin => "Sakhalin",
        Tz::Asia__Samarkand => "Samarkand",
        Tz::Asia__Seoul => "Seoul",
        Tz::Asia__Shanghai => "Shanghai",
        Tz::Asia__Singapore => "Singapore",
        Tz::Asia__Srednekolymsk => "Srednekolymsk",
        Tz::Asia__Taipei => "Taipei",
        Tz::Asia__Tashkent => "Tashkent",
        Tz::Asia__Tbilisi => "Tbilisi",
        Tz::Asia__Tehran => "Tehran",
        Tz::Asia__Tel_Aviv => "Tel_Aviv",
        Tz::Asia__Thimbu => "Thimbu",
        Tz::Asia__Thimphu => "Thimphu",
        Tz::Asia__Tokyo => "Tokyo",
        Tz::Asia__Tomsk => "Tomsk",
        Tz::Asia__Ujung_Pandang => "Ujung Pandang",
        Tz::Asia__Ulaanbaatar => "Ulaanbaatar",
        Tz::Asia__Ulan_Bator => "Ulan_Bator",
        Tz::Asia__Urumqi => "Urumqi",
        Tz::Asia__UstNera => "Ust-Nera",
        Tz::Asia__Vientiane => "Vientiane",
        Tz::Asia__Vladivostok => "Vladivostok",
        Tz::Asia__Yakutsk => "Yakutsk",
        Tz::Asia__Yangon => "Yangon",
        Tz::Asia__Yekaterinburg => "Yekaterinburg",
        Tz::Asia__Yerevan => "Yerevan",
        Tz::Atlantic__Azores => "Azores",
        Tz::Atlantic__Bermuda => "Bermuda",
        Tz::Atlantic__Canary => "Canary",
        Tz::Atlantic__Cape_Verde => "Cape_Verde",
        Tz::Atlantic__Faeroe => "Faeroe",
        Tz::Atlantic__Faroe => "Faroe",
        Tz::Atlantic__Jan_Mayen => "Jan Mayen",
        Tz::Atlantic__Madeira => "Madeira",
        Tz::Atlantic__Reykjavik => "Reykjavik",
        Tz::Atlantic__South_Georgia => "South_Georgia",
        Tz::Atlantic__St_Helena => "St_Helena",
        Tz::Atlantic__Stanley => "Stanley",
        Tz::Australia__ACT => "ACT",
        Tz::Australia__Adelaide => "Adelaide",
        Tz::Australia__Brisbane => "Brisbane",
        Tz::Australia__Broken_Hill => "Broken Hill",
        Tz::Australia__Canberra => "Canberra",
        Tz::Australia__Currie => "Currie",
        Tz::Australia__Darwin => "Darwin",
        Tz::Australia__Eucla => "Eucla",
        Tz::Australia__Hobart => "Hobart",
        Tz::Australia__LHI => "LHI",
        Tz::Australia__Lindeman => "Lindeman",
        Tz::Australia__Lord_Howe => "Lord Howe",
        Tz::Australia__Melbourne => "Melbourne",
        Tz::Australia__NSW => "NSW",
        Tz::Australia__North => "North",
        Tz::Australia__Perth => "Perth",
        Tz::Australia__Queensland => "Queensland",
        Tz::Australia__South => "South",
        Tz::Australia__Sydney => "Sydney",
        Tz::Australia__Tasmania => "Tasmania",
        Tz::Australia__Victoria => "Victoria",
        Tz::Australia__West => "West",
        Tz::Australia__Yancowinna => "Yancowinna",
        Tz::Brazil__Acre => "Brazil Acre",
        Tz::Brazil__DeNoronha => "Brazil DeNoronha",
        Tz::Brazil__East => "Brazil East",
        Tz::Brazil__West => "Brazil West",
        Tz::CET => "CET",
        Tz::CST6CDT => "CST6CDT",
        Tz::Canada__Atlantic => "Canada Atlantic",
        Tz::Canada__Central => "Canada Central",
        Tz::Canada__Eastern => "Canada Eastern",
        Tz::Canada__Mountain => "Canada Mountain",
        Tz::Canada__Newfoundland => "Canada Newfoundland",
        Tz::Canada__Pacific => "Canada Pacific",
        Tz::Canada__Saskatchewan => "Canada Saskatchewan",
        Tz::Canada__Yukon => "Canada Yukon",
        Tz::Chile__Continental => "Chile Continental",
        Tz::Chile__EasterIsland => "Chile EasterIsland",
        Tz::Cuba => "Cuba",
        Tz::EET => "EET",
        Tz::EST => "EST",
        Tz::EST5EDT => "EST5EDT",
        Tz::Egypt => "Egypt",
        Tz::Eire => "Eire",
        Tz::Etc__GMT => "GMT",
        Tz::Etc__GMTPlus0 => "GMT+0",
        Tz::Etc__GMTPlus1 => "GMT+1",
        Tz::Etc__GMTPlus10 => "GMT+10",
        Tz::Etc__GMTPlus11 => "GMT+11",
        Tz::Etc__GMTPlus12 => "GMT+12",
        Tz::Etc__GMTPlus2 => "GMT+2",
        Tz::Etc__GMTPlus3 => "GMT+3",
        Tz::Etc__GMTPlus4 => "GMT+4",
        Tz::Etc__GMTPlus5 => "GMT+5",
        Tz::Etc__GMTPlus6 => "GMT+6",
        Tz::Etc__GMTPlus7 => "GMT+7",
        Tz::Etc__GMTPlus8 => "GMT+8",
        Tz::Etc__GMTPlus9 => "GMT+9",
        Tz::Etc__GMTMinus0 => "GMT-0",
        Tz::Etc__GMTMinus1 => "GMT-1",
        Tz::Etc__GMTMinus10 => "GMT-10",
        Tz::Etc__GMTMinus11 => "GMT-11",
        Tz::Etc__GMTMinus12 => "GMT-12",
        Tz::Etc__GMTMinus13 => "GMT-13",
        Tz::Etc__GMTMinus14 => "GMT-14",
        Tz::Etc__GMTMinus2 => "GMT-2",
        Tz::Etc__GMTMinus3 => "GMT-3",
        Tz::Etc__GMTMinus4 => "GMT-4",
        Tz::Etc__GMTMinus5 => "GMT-5",
        Tz::Etc__GMTMinus6 => "GMT-6",
        Tz::Etc__GMTMinus7 => "GMT-7",
        Tz::Etc__GMTMinus8 => "GMT-8",
        Tz::Etc__GMTMinus9 => "GMT-9",
        Tz::Etc__GMT0 => "GMT0",
        Tz::Etc__Greenwich => "Greenwich",
        Tz::Etc__UCT => "UCT",
        Tz::Etc__UTC => "UTC",
        Tz::Etc__Universal => "Universal",
        Tz::Etc__Zulu => "Zulu",
        Tz::Europe__Amsterdam => "Amsterdam",
        Tz::Europe__Andorra => "Andorra",
        Tz::Europe__Astrakhan => "Astrakhan",
        Tz::Europe__Athens => "Athens",
        Tz::Europe__Belfast => "Belfast",
        Tz::Europe__Belgrade => "Belgrade",
        Tz::Europe__Berlin => "Berlin",
        Tz::Europe__Bratislava => "Bratislava",
        Tz::Europe__Brussels => "Brussels",
        Tz::Europe__Bucharest => "Bucharest",
        Tz::Europe__Budapest => "Budapest",
        Tz::Europe__Busingen => "Busingen",
        Tz::Europe__Chisinau => "Chisinau",
        Tz::Europe__Copenhagen => "Copenhagen",
        Tz::Europe__Dublin => "Dublin",
        Tz::Europe__Gibraltar => "Gibraltar",
        Tz::Europe__Guernsey => "Guernsey",
        Tz::Europe__Helsinki => "Helsinki",
        Tz::Europe__Isle_of_Man => "Isle of Man",
        Tz::Europe__Istanbul => "Istanbul",
        Tz::Europe__Jersey => "Jersey",
        Tz::Europe__Kaliningrad => "Kaliningrad",
        Tz::Europe__Kiev => "Kiev",
        Tz::Europe__Kirov => "Kirov",
        Tz::Europe__Kyiv => "Kyiv",
        Tz::Europe__Lisbon => "Lisbon",
        Tz::Europe__Ljubljana => "Ljubljana",
        Tz::Europe__London => "London",
        Tz::Europe__Luxembourg => "Luxembourg",
        Tz::Europe__Madrid => "Madrid",
        Tz::Europe__Malta => "Malta",
        Tz::Europe__Mariehamn => "Mariehamn",
        Tz::Europe__Minsk => "Minsk",
        Tz::Europe__Monaco => "Monaco",
        Tz::Europe__Moscow => "Moscow",
        Tz::Europe__Nicosia => "Nicosia",
        Tz::Europe__Oslo => "Oslo",
        Tz::Europe__Paris => "Paris",
        Tz::Europe__Podgorica => "Podgorica",
        Tz::Europe__Prague => "Prague",
        Tz::Europe__Riga => "Riga",
        Tz::Europe__Rome => "Rome",
        Tz::Europe__Samara => "Samara",
        Tz::Europe__San_Marino => "San_Marino",
        Tz::Europe__Sarajevo => "Sarajevo",
        Tz::Europe__Saratov => "Saratov",
        Tz::Europe__Simferopol => "Simferopol",
        Tz::Europe__Skopje => "Skopje",
        Tz::Europe__Sofia => "Sofia",
        Tz::Europe__Stockholm => "Stockholm",
        Tz::Europe__Tallinn => "Tallinn",
        Tz::Europe__Tirane => "Tirane",
        Tz::Europe__Tiraspol => "Tiraspol",
        Tz::Europe__Ulyanovsk => "Ulyanovsk",
        Tz::Europe__Uzhgorod => "Uzhgorod",
        Tz::Europe__Vaduz => "Vaduz",
        Tz::Europe__Vatican => "Vatican",
        Tz::Europe__Vienna => "Vienna",
        Tz::Europe__Vilnius => "Vilnius",
        Tz::Europe__Volgograd => "Volgograd",
        Tz::Europe__Warsaw => "Warsaw",
        Tz::Europe__Zagreb => "Zagreb",
        Tz::Europe__Zaporozhye => "Zaporozhye",
        Tz::Europe__Zurich => "Zurich",
        Tz::GB => "GB",
        Tz::GBEire => "GB-Eire",
        Tz::GMT => "GMT",
        Tz::GMTPlus0 => "GMT+0",
        Tz::GMTMinus0 => "GMT-0",
        Tz::GMT0 => "GMT0",
        Tz::Greenwich => "Greenwich",
        Tz::HST => "HST",
        Tz::Hongkong => "Hongkong",
        Tz::Iceland => "Iceland",
        Tz::Indian__Antananarivo => "Antananarivo",
        Tz::Indian__Chagos => "Chagos",
        Tz::Indian__Christmas => "Christmas Island",
        Tz::Indian__Cocos => "Cocos Islands",
        Tz::Indian__Comoro => "Indian/Comoro",
        Tz::Indian__Kerguelen => "Kerguelen Islands",
        Tz::Indian__Mahe => "Mahe",
        Tz::Indian__Maldives => "Maldives",
        Tz::Indian__Mauritius => "Mauritius",
        Tz::Indian__Mayotte => "Mayotte Island",
        Tz::Indian__Reunion => "Reunion Island",
        Tz::Iran => "Iran",
        Tz::Israel => "Israel",
        Tz::Jamaica => "Jamaica",
        Tz::Japan => "Japan",
        Tz::Kwajalein => "Kwajalein",
        Tz::Libya => "Libya",
        Tz::MET => "MET",
        Tz::MST => "MST",
        Tz::MST7MDT => "MST7MDT",
        Tz::Mexico__BajaNorte => "Mexico BajaNorte",
        Tz::Mexico__BajaSur => "Mexico BajaSur",
        Tz::Mexico__General => "Mexico General",
        Tz::NZ => "NZ",
        Tz::NZCHAT => "NZ-CHAT",
        Tz::Navajo => "Navajo",
        Tz::PRC => "PRC",
        Tz::PST8PDT => "PST8PDT",
        Tz::Pacific__Apia => "Pacific Apia",
        Tz::Pacific__Auckland => "Pacific Auckland",
        Tz::Pacific__Bougainville => "Pacific Bougainville",
        Tz::Pacific__Chatham => "Pacific Chatham",
        Tz::Pacific__Chuuk => "Pacific Chuuk",
        Tz::Pacific__Easter => "Pacific Easter",
        Tz::Pacific__Efate => "Pacific Efate",
        Tz::Pacific__Enderbury => "Pacific Enderbury",
        Tz::Pacific__Fakaofo => "Pacific Fakaofo",
        Tz::Pacific__Fiji => "Pacific Fiji",
        Tz::Pacific__Funafuti => "Pacific Funafuti",
        Tz::Pacific__Galapagos => "Pacific Galapagos",
        Tz::Pacific__Gambier => "Pacific Gambier",
        Tz::Pacific__Guadalcanal => "Pacific Guadalcanal",
        Tz::Pacific__Guam => "Pacific Guam",
        Tz::Pacific__Honolulu => "Pacific Honolulu",
        Tz::Pacific__Johnston => "Pacific Johnston",
        Tz::Pacific__Kanton => "Pacific Kanton",
        Tz::Pacific__Kiritimati => "Pacific Kiritimati",
        Tz::Pacific__Kosrae => "Pacific Kosrae",
        Tz::Pacific__Kwajalein => "Pacific Kwajalein",
        Tz::Pacific__Majuro => "Pacific Majuro",
        Tz::Pacific__Marquesas => "Pacific Marquesas",
        Tz::Pacific__Midway => "Pacific Midway",
        Tz::Pacific__Nauru => "Pacific Nauru",
        Tz::Pacific__Niue => "Pacific Niue",
        Tz::Pacific__Norfolk => "Pacific Norfolk",
        Tz::Pacific__Noumea => "Pacific Noumea",
        Tz::Pacific__Pago_Pago => "Pacific Pago Pago",
        Tz::Pacific__Palau => "Pacific Palau",
        Tz::Pacific__Pitcairn => "Pacific Pitcairn",
        Tz::Pacific__Pohnpei => "Pacific Pohnpei",
        Tz::Pacific__Ponape => "Pacific Ponape",
        Tz::Pacific__Port_Moresby => "Pacific Port Moresby",
        Tz::Pacific__Rarotonga => "Pacific Rarotonga",
        Tz::Pacific__Saipan => "Pacific Saipan",
        Tz::Pacific__Samoa => "Pacific Samoa",
        Tz::Pacific__Tahiti => "Pacific Tahiti",
        Tz::Pacific__Tarawa => "Pacific Tarawa",
        Tz::Pacific__Tongatapu => "Pacific Tongatapu",
        Tz::Pacific__Truk => "Pacific Truk",
        Tz::Pacific__Wake => "Pacific Wake",
        Tz::Pacific__Wallis => "Pacific Wallis",
        Tz::Pacific__Yap => "Pacific Yap",
        Tz::Poland => "Poland",
        Tz::Portugal => "Portugal",
        Tz::ROC => "ROC",
        Tz::ROK => "ROK",
        Tz::Singapore => "Singapore",
        Tz::Turkey => "Turkey",
        Tz::UCT => "UCT",
        Tz::US__Alaska => "US Alaska",
        Tz::US__Aleutian => "US Aleutian",
        Tz::US__Arizona => "US Arizona",
        Tz::US__Central => "US Central",
        Tz::US__EastIndiana => "US East-Indiana",
        Tz::US__Eastern => "US Eastern",
        Tz::US__Hawaii => "US Hawaii",
        Tz::US__IndianaStarke => "US Indiana-Starke",
        Tz::US__Michigan => "US Michigan",
        Tz::US__Mountain => "US Mountain",
        Tz::US__Pacific => "US Pacific",
        Tz::US__Samoa => "US Samoa",
        Tz::UTC => "UTC",
        Tz::Universal => "Universal",
        Tz::WSU => "W-SU",
        Tz::WET => "WET",
        Tz::Zulu => "Zulu",
    }
    .to_string()
}

pub fn tz_to_country(timezone: &Tz) -> String {
    match timezone {
        Tz::Africa__Abidjan => "Côte d'Ivoire",
        Tz::Africa__Accra => "Ghana",
        Tz::Africa__Addis_Ababa => "Ethiopia",
        Tz::Africa__Algiers => "Algeria",
        Tz::Africa__Asmara => "Eritrea",
        Tz::Africa__Asmera => "Eritrea",
        Tz::Africa__Bamako => "Mali",
        Tz::Africa__Bangui => "Central African Republic",
        Tz::Africa__Banjul => "Gambia",
        Tz::Africa__Bissau => "Guinea-Bissau",
        Tz::Africa__Blantyre => "Malawi",
        Tz::Africa__Brazzaville => "Republic of the Congo",
        Tz::Africa__Bujumbura => "Burundi",
        Tz::Africa__Cairo => "Egypt",
        Tz::Africa__Casablanca => "Morocco",
        Tz::Africa__Ceuta => "Spain",
        Tz::Africa__Conakry => "Guinea",
        Tz::Africa__Dakar => "Senegal",
        Tz::Africa__Dar_es_Salaam => "Tanzania",
        Tz::Africa__Djibouti => "Djibouti",
        Tz::Africa__Douala => "Cameroon",
        Tz::Africa__El_Aaiun => "Western Sahara",
        Tz::Africa__Freetown => "Sierra Leone",
        Tz::Africa__Gaborone => "Botswana",
        Tz::Africa__Harare => "Zimbabwe",
        Tz::Africa__Johannesburg => "South Africa",
        Tz::Africa__Juba => "South Sudan",
        Tz::Africa__Kampala => "Uganda",
        Tz::Africa__Khartoum => "Sudan",
        Tz::Africa__Kigali => "Rwanda",
        Tz::Africa__Kinshasa => "Democratic Republic of the Congo",
        Tz::Africa__Lagos => "Nigeria",
        Tz::Africa__Libreville => "Gabon",
        Tz::Africa__Lome => "Togo",
        Tz::Africa__Luanda => "Angola",
        Tz::Africa__Lubumbashi => "Democratic Republic of the Congo",
        Tz::Africa__Lusaka => "Zambia",
        Tz::Africa__Malabo => "Equatorial Guinea",
        Tz::Africa__Maputo => "Mozambique",
        Tz::Africa__Maseru => "Lesotho",
        Tz::Africa__Mbabane => "Eswatini",
        Tz::Africa__Mogadishu => "Somalia",
        Tz::Africa__Monrovia => "Liberia",
        Tz::Africa__Nairobi => "Kenya",
        Tz::Africa__Ndjamena => "Chad",
        Tz::Africa__Niamey => "Niger",
        Tz::Africa__Nouakchott => "Mauritania",
        Tz::Africa__Ouagadougou => "Burkina Faso",
        Tz::Africa__PortoNovo => "Benin",
        Tz::Africa__Sao_Tome => "São Tomé and Príncipe",
        Tz::Africa__Timbuktu => "Mali",
        Tz::Africa__Tripoli => "Libya",
        Tz::Africa__Tunis => "Tunisia",
        Tz::Africa__Windhoek => "Namibia",
        Tz::America__Adak => "United States",
        Tz::America__Anchorage => "United States",
        Tz::America__Anguilla => "Anguilla",
        Tz::America__Antigua => "Antigua and Barbuda",
        Tz::America__Araguaina => "Brazil",
        Tz::America__Argentina__Buenos_Aires => "Argentina",
        Tz::America__Argentina__Catamarca => "Argentina",
        Tz::America__Argentina__ComodRivadavia => "Argentina",
        Tz::America__Argentina__Cordoba => "Argentina",
        Tz::America__Argentina__Jujuy => "Argentina",
        Tz::America__Argentina__La_Rioja => "Argentina",
        Tz::America__Argentina__Mendoza => "Argentina",
        Tz::America__Argentina__Rio_Gallegos => "Argentina",
        Tz::America__Argentina__Salta => "Argentina",
        Tz::America__Argentina__San_Juan => "Argentina",
        Tz::America__Argentina__San_Luis => "Argentina",
        Tz::America__Argentina__Tucuman => "Argentina",
        Tz::America__Argentina__Ushuaia => "Argentina",
        Tz::America__Aruba => "Aruba",
        Tz::America__Asuncion => "Paraguay",
        Tz::America__Atikokan => "Canada",
        Tz::America__Atka => "United States",
        Tz::America__Bahia => "Brazil",
        Tz::America__Bahia_Banderas => "Mexico",
        Tz::America__Barbados => "Barbados",
        Tz::America__Belem => "Brazil",
        Tz::America__Belize => "Belize",
        Tz::America__BlancSablon => "Canada",
        Tz::America__Boa_Vista => "Brazil",
        Tz::America__Bogota => "Colombia",
        Tz::America__Boise => "United States",
        Tz::America__Buenos_Aires => "Argentina",
        Tz::America__Cambridge_Bay => "Canada",
        Tz::America__Campo_Grande => "Brazil",
        Tz::America__Cancun => "Mexico",
        Tz::America__Caracas => "Venezuela",
        Tz::America__Catamarca => "Argentina",
        Tz::America__Cayenne => "French Guiana",
        Tz::America__Cayman => "Cayman Islands",
        Tz::America__Chicago => "United States",
        Tz::America__Chihuahua => "Mexico",
        Tz::America__Ciudad_Juarez => "Mexico",
        Tz::America__Coral_Harbour => "Canada",
        Tz::America__Cordoba => "Argentina",
        Tz::America__Costa_Rica => "Costa Rica",
        Tz::America__Coyhaique => "Chile",
        Tz::America__Creston => "Canada",
        Tz::America__Cuiaba => "Brazil",
        Tz::America__Curacao => "Curaçao",
        Tz::America__Danmarkshavn => "Greenland",
        Tz::America__Dawson => "Canada",
        Tz::America__Dawson_Creek => "Canada",
        Tz::America__Denver => "United States",
        Tz::America__Detroit => "United States",
        Tz::America__Dominica => "Dominica",
        Tz::America__Edmonton => "Canada",
        Tz::America__Eirunepe => "Brazil",
        Tz::America__El_Salvador => "El Salvador",
        Tz::America__Ensenada => "Mexico",
        Tz::America__Fort_Nelson => "Canada",
        Tz::America__Fort_Wayne => "United States",
        Tz::America__Fortaleza => "Brazil",
        Tz::America__Glace_Bay => "Canada",
        Tz::America__Godthab => "Greenland",
        Tz::America__Goose_Bay => "Canada",
        Tz::America__Grand_Turk => "Turks and Caicos Islands",
        Tz::America__Grenada => "Grenada",
        Tz::America__Guadeloupe => "Guadeloupe",
        Tz::America__Guatemala => "Guatemala",
        Tz::America__Guayaquil => "Ecuador",
        Tz::America__Guyana => "Guyana",
        Tz::America__Halifax => "Canada",
        Tz::America__Havana => "Cuba",
        Tz::America__Hermosillo => "Mexico",
        Tz::America__Indiana__Indianapolis => "United States",
        Tz::America__Indiana__Knox => "United States",
        Tz::America__Indiana__Marengo => "United States",
        Tz::America__Indiana__Petersburg => "United States",
        Tz::America__Indiana__Tell_City => "United States",
        Tz::America__Indiana__Vevay => "United States",
        Tz::America__Indiana__Vincennes => "United States",
        Tz::America__Indiana__Winamac => "United States",
        Tz::America__Indianapolis => "United States",
        Tz::America__Inuvik => "Canada",
        Tz::America__Iqaluit => "Canada",
        Tz::America__Jamaica => "Jamaica",
        Tz::America__Jujuy => "Argentina",
        Tz::America__Juneau => "United States",
        Tz::America__Kentucky__Louisville => "United States",
        Tz::America__Kentucky__Monticello => "United States",
        Tz::America__Knox_IN => "United States",
        Tz::America__Kralendijk => "Caribbean Netherlands",
        Tz::America__La_Paz => "Bolivia",
        Tz::America__Lima => "Peru",
        Tz::America__Los_Angeles => "United States",
        Tz::America__Louisville => "United States",
        Tz::America__Lower_Princes => "Saint Martin",
        Tz::America__Maceio => "Brazil",
        Tz::America__Managua => "Nicaragua",
        Tz::America__Manaus => "Brazil",
        Tz::America__Marigot => "France",
        Tz::America__Martinique => "France",
        Tz::America__Matamoros => "Mexico",
        Tz::America__Mazatlan => "Mexico",
        Tz::America__Mendoza => "Argentina",
        Tz::America__Menominee => "United States",
        Tz::America__Merida => "Mexico",
        Tz::America__Metlakatla => "United States",
        Tz::America__Mexico_City => "Mexico",
        Tz::America__Miquelon => "France",
        Tz::America__Moncton => "Canada",
        Tz::America__Monterrey => "Mexico",
        Tz::America__Montevideo => "Uruguay",
        Tz::America__Montreal => "Canada",
        Tz::America__Montserrat => "Montserrat",
        Tz::America__Nassau => "Bahamas",
        Tz::America__New_York => "United States",
        Tz::America__Nipigon => "Canada",
        Tz::America__Nome => "United States",
        Tz::America__Noronha => "Brazil",
        Tz::America__North_Dakota__Beulah => "United States",
        Tz::America__North_Dakota__Center => "United States",
        Tz::America__North_Dakota__New_Salem => "United States",
        Tz::America__Nuuk => "Greenland",
        Tz::America__Ojinaga => "Mexico",
        Tz::America__Panama => "Panama",
        Tz::America__Pangnirtung => "Canada",
        Tz::America__Paramaribo => "Suriname",
        Tz::America__Phoenix => "United States",
        Tz::America__PortauPrince => "Haiti",
        Tz::America__Port_of_Spain => "Trinidad and Tobago",
        Tz::America__Porto_Acre => "Brazil",
        Tz::America__Porto_Velho => "Brazil",
        Tz::America__Puerto_Rico => "Puerto Rico",
        Tz::America__Punta_Arenas => "Chile",
        Tz::America__Rainy_River => "Canada",
        Tz::America__Rankin_Inlet => "Canada",
        Tz::America__Recife => "Brazil",
        Tz::America__Regina => "Canada",
        Tz::America__Resolute => "Canada",
        Tz::America__Rio_Branco => "Brazil",
        Tz::America__Rosario => "Argentina",
        Tz::America__Santa_Isabel => "Mexico",
        Tz::America__Santarem => "Brazil",
        Tz::America__Santiago => "Chile",
        Tz::America__Santo_Domingo => "Dominican Republic",
        Tz::America__Sao_Paulo => "Brazil",
        Tz::America__Scoresbysund => "Greenland",
        Tz::America__Shiprock => "United States",
        Tz::America__Sitka => "United States",
        Tz::America__St_Barthelemy => "Saint Barthélemy",
        Tz::America__St_Johns => "Canada",
        Tz::America__St_Kitts => "Saint Kitts and Nevis",
        Tz::America__St_Lucia => "Saint Lucia",
        Tz::America__St_Thomas => "United States Virgin Islands",
        Tz::America__St_Vincent => "Saint Vincent and the Grenadines",
        Tz::America__Swift_Current => "Canada",
        Tz::America__Tegucigalpa => "Honduras",
        Tz::America__Thule => "Greenland",
        Tz::America__Thunder_Bay => "Canada",
        Tz::America__Tijuana => "Mexico",
        Tz::America__Toronto => "Canada",
        Tz::America__Tortola => "United States",
        Tz::America__Vancouver => "Canada",
        Tz::America__Virgin => "United States",
        Tz::America__Whitehorse => "Canada",
        Tz::America__Winnipeg => "Canada",
        Tz::America__Yakutat => "United States",
        Tz::America__Yellowknife => "Canada",
        Tz::Antarctica__Casey => "Antarctica",
        Tz::Antarctica__Davis => "Antarctica",
        Tz::Antarctica__DumontDUrville => "Antarctica",
        Tz::Antarctica__Macquarie => "Antarctica",
        Tz::Antarctica__Mawson => "Antarctica",
        Tz::Antarctica__McMurdo => "Antarctica",
        Tz::Antarctica__Palmer => "Antarctica",
        Tz::Antarctica__Rothera => "Antarctica",
        Tz::Antarctica__South_Pole => "Antarctica",
        Tz::Antarctica__Syowa => "Antarctica",
        Tz::Antarctica__Troll => "Antarctica",
        Tz::Antarctica__Vostok => "Antarctica",
        Tz::Arctic__Longyearbyen => "Norway",
        Tz::Asia__Aden => "Yemen",
        Tz::Asia__Almaty => "Kazakhstan",
        Tz::Asia__Amman => "Jordan",
        Tz::Asia__Anadyr => "Russia",
        Tz::Asia__Aqtau => "Kazakhstan",
        Tz::Asia__Aqtobe => "Kazakhstan",
        Tz::Asia__Ashgabat => "Turkmenistan",
        Tz::Asia__Ashkhabad => "Turkmenistan",
        Tz::Asia__Atyrau => "Kazakhstan",
        Tz::Asia__Baghdad => "Iraq",
        Tz::Asia__Bahrain => "Bahrain",
        Tz::Asia__Baku => "Azerbaijan",
        Tz::Asia__Bangkok => "Thailand",
        Tz::Asia__Barnaul => "Russia",
        Tz::Asia__Beirut => "Lebanon",
        Tz::Asia__Bishkek => "Kyrgyzstan",
        Tz::Asia__Brunei => "Brunei",
        Tz::Asia__Calcutta => "India",
        Tz::Asia__Chita => "Russia",
        Tz::Asia__Choibalsan => "Mongolia",
        Tz::Asia__Chongqing => "China",
        Tz::Asia__Chungking => "China",
        Tz::Asia__Colombo => "Sri Lanka",
        Tz::Asia__Dacca => "Bangladesh",
        Tz::Asia__Damascus => "Syria",
        Tz::Asia__Dhaka => "Bangladesh",
        Tz::Asia__Dili => "East Timor",
        Tz::Asia__Dubai => "United Arab Emirates",
        Tz::Asia__Dushanbe => "Tajikistan",
        Tz::Asia__Famagusta => "Cyprus",
        Tz::Asia__Gaza => "Palestine",
        Tz::Asia__Harbin => "China",
        Tz::Asia__Hebron => "Palestine",
        Tz::Asia__Ho_Chi_Minh => "Vietnam",
        Tz::Asia__Hong_Kong => "China",
        Tz::Asia__Hovd => "Mongolia",
        Tz::Asia__Irkutsk => "Russia",
        Tz::Asia__Istanbul => "Turkey",
        Tz::Asia__Jakarta => "Indonesia",
        Tz::Asia__Jayapura => "Indonesia",
        Tz::Asia__Jerusalem => "Israel",
        Tz::Asia__Kabul => "Afghanistan",
        Tz::Asia__Kamchatka => "Russia",
        Tz::Asia__Karachi => "Pakistan",
        Tz::Asia__Kashgar => "China",
        Tz::Asia__Kathmandu => "Nepal",
        Tz::Asia__Katmandu => "Nepal",
        Tz::Asia__Khandyga => "Russia",
        Tz::Asia__Kolkata => "India",
        Tz::Asia__Krasnoyarsk => "Russia",
        Tz::Asia__Kuala_Lumpur => "Malaysia",
        Tz::Asia__Kuching => "Malaysia",
        Tz::Asia__Kuwait => "Kuwait",
        Tz::Asia__Macao => "Macao",
        Tz::Asia__Macau => "Macau",
        Tz::Asia__Magadan => "Russia",
        Tz::Asia__Makassar => "Indonesia",
        Tz::Asia__Manila => "Philippines",
        Tz::Asia__Muscat => "Oman",
        Tz::Asia__Nicosia => "Cyprus",
        Tz::Asia__Novokuznetsk => "Russia",
        Tz::Asia__Novosibirsk => "Russia",
        Tz::Asia__Omsk => "Russia",
        Tz::Asia__Oral => "Kazakhstan",
        Tz::Asia__Phnom_Penh => "Cambodia",
        Tz::Asia__Pontianak => "Indonesia",
        Tz::Asia__Pyongyang => "North Korea",
        Tz::Asia__Qatar => "Qatar",
        Tz::Asia__Qostanay => "Kazakhstan",
        Tz::Asia__Qyzylorda => "Kazakhstan",
        Tz::Asia__Rangoon => "Myanmar",
        Tz::Asia__Riyadh => "Saudi Arabia",
        Tz::Asia__Saigon => "Vietnam",
        Tz::Asia__Sakhalin => "Russia",
        Tz::Asia__Samarkand => "Uzbekistan",
        Tz::Asia__Seoul => "South Korea",
        Tz::Asia__Shanghai => "China",
        Tz::Asia__Singapore => "",
        Tz::Asia__Srednekolymsk => "Russia",
        Tz::Asia__Taipei => "Taiwan",
        Tz::Asia__Tashkent => "Uzbekistan",
        Tz::Asia__Tbilisi => "Georgia",
        Tz::Asia__Tehran => "Iran",
        Tz::Asia__Tel_Aviv => "Israel",
        Tz::Asia__Thimbu => "Bhutan",
        Tz::Asia__Thimphu => "Bhutan",
        Tz::Asia__Tokyo => "Japan",
        Tz::Asia__Tomsk => "Russia",
        Tz::Asia__Ujung_Pandang => "Indonesia",
        Tz::Asia__Ulaanbaatar => "Mongolia",
        Tz::Asia__Ulan_Bator => "Mongolia",
        Tz::Asia__Urumqi => "China",
        Tz::Asia__UstNera => "Russia",
        Tz::Asia__Vientiane => "Laos",
        Tz::Asia__Vladivostok => "Russia",
        Tz::Asia__Yakutsk => "Russia",
        Tz::Asia__Yangon => "Myanmar",
        Tz::Asia__Yekaterinburg => "Russia",
        Tz::Asia__Yerevan => "Armenia",
        Tz::Atlantic__Azores => "Portugal",
        Tz::Atlantic__Bermuda => "Bermuda",
        Tz::Atlantic__Canary => "Spain",
        Tz::Atlantic__Cape_Verde => "Cape Verde",
        Tz::Atlantic__Faeroe => "Faroe Islands",
        Tz::Atlantic__Faroe => "Faroe Islands",
        Tz::Atlantic__Jan_Mayen => "Norway",
        Tz::Atlantic__Madeira => "Portugal",
        Tz::Atlantic__Reykjavik => "Iceland",
        Tz::Atlantic__South_Georgia => "South Georgia and the South Sandwich Islands",
        Tz::Atlantic__St_Helena => "Saint Helena",
        Tz::Atlantic__Stanley => "Falkland Islands",
        Tz::Australia__ACT => "Australia",
        Tz::Australia__Adelaide => "Australia",
        Tz::Australia__Brisbane => "Australia",
        Tz::Australia__Broken_Hill => "Australia",
        Tz::Australia__Canberra => "Australia",
        Tz::Australia__Currie => "Australia",
        Tz::Australia__Darwin => "Australia",
        Tz::Australia__Eucla => "Australia",
        Tz::Australia__Hobart => "Australia",
        Tz::Australia__LHI => "Australia",
        Tz::Australia__Lindeman => "Australia",
        Tz::Australia__Lord_Howe => "Australia",
        Tz::Australia__Melbourne => "Australia",
        Tz::Australia__NSW => "Australia",
        Tz::Australia__North => "Australia",
        Tz::Australia__Perth => "Australia",
        Tz::Australia__Queensland => "Australia",
        Tz::Australia__South => "Australia",
        Tz::Australia__Sydney => "Australia",
        Tz::Australia__Tasmania => "Australia",
        Tz::Australia__Victoria => "Australia",
        Tz::Australia__West => "Australia",
        Tz::Australia__Yancowinna => "Australia",
        Tz::Brazil__Acre => "Brazil",
        Tz::Brazil__DeNoronha => "Brazil",
        Tz::Brazil__East => "Brazil",
        Tz::Brazil__West => "Brazil",
        Tz::CET => "",
        Tz::CST6CDT => "",
        Tz::Canada__Atlantic => "Canada",
        Tz::Canada__Central => "Canada",
        Tz::Canada__Eastern => "Canada",
        Tz::Canada__Mountain => "Canada",
        Tz::Canada__Newfoundland => "Canada",
        Tz::Canada__Pacific => "Canada",
        Tz::Canada__Saskatchewan => "Canada",
        Tz::Canada__Yukon => "Canada",
        Tz::Chile__Continental => "Chile",
        Tz::Chile__EasterIsland => "Chile",
        Tz::Cuba => "",
        Tz::EET => "",
        Tz::EST => "",
        Tz::EST5EDT => "",
        Tz::Egypt => "Egypt",
        Tz::Eire => "Ireland",
        Tz::Etc__GMT => "United Kingdom",
        Tz::Etc__GMTPlus0 => "",
        Tz::Etc__GMTPlus1 => "",
        Tz::Etc__GMTPlus10 => "",
        Tz::Etc__GMTPlus11 => "",
        Tz::Etc__GMTPlus12 => "",
        Tz::Etc__GMTPlus2 => "",
        Tz::Etc__GMTPlus3 => "",
        Tz::Etc__GMTPlus4 => "",
        Tz::Etc__GMTPlus5 => "",
        Tz::Etc__GMTPlus6 => "",
        Tz::Etc__GMTPlus7 => "",
        Tz::Etc__GMTPlus8 => "",
        Tz::Etc__GMTPlus9 => "",
        Tz::Etc__GMTMinus0 => "",
        Tz::Etc__GMTMinus1 => "",
        Tz::Etc__GMTMinus10 => "",
        Tz::Etc__GMTMinus11 => "",
        Tz::Etc__GMTMinus12 => "",
        Tz::Etc__GMTMinus13 => "",
        Tz::Etc__GMTMinus14 => "",
        Tz::Etc__GMTMinus2 => "",
        Tz::Etc__GMTMinus3 => "",
        Tz::Etc__GMTMinus4 => "",
        Tz::Etc__GMTMinus5 => "",
        Tz::Etc__GMTMinus6 => "",
        Tz::Etc__GMTMinus7 => "",
        Tz::Etc__GMTMinus8 => "",
        Tz::Etc__GMTMinus9 => "",
        Tz::Etc__GMT0 => "",
        Tz::Etc__Greenwich => "United Kingdom",
        Tz::Etc__UCT => "",
        Tz::Etc__UTC => "",
        Tz::Etc__Universal => "",
        Tz::Etc__Zulu => "",
        Tz::Europe__Amsterdam => "Netherlands",
        Tz::Europe__Andorra => "Andorra",
        Tz::Europe__Astrakhan => "Russia",
        Tz::Europe__Athens => "Greece",
        Tz::Europe__Belfast => "United Kingdom",
        Tz::Europe__Belgrade => "Serbia",
        Tz::Europe__Berlin => "Germany",
        Tz::Europe__Bratislava => "Slovakia",
        Tz::Europe__Brussels => "Belgium",
        Tz::Europe__Bucharest => "Romania",
        Tz::Europe__Budapest => "Hungary",
        Tz::Europe__Busingen => "Germany",
        Tz::Europe__Chisinau => "Moldova",
        Tz::Europe__Copenhagen => "Denmark",
        Tz::Europe__Dublin => "Ireland",
        Tz::Europe__Gibraltar => "Gibraltar",
        Tz::Europe__Guernsey => "Guernsey",
        Tz::Europe__Helsinki => "Finland",
        Tz::Europe__Isle_of_Man => "Isle of Man",
        Tz::Europe__Istanbul => "Turkey",
        Tz::Europe__Jersey => "Jersey",
        Tz::Europe__Kaliningrad => "Russia",
        Tz::Europe__Kiev => "Ukraine",
        Tz::Europe__Kirov => "Russia",
        Tz::Europe__Kyiv => "Ukraine",
        Tz::Europe__Lisbon => "Portugal",
        Tz::Europe__Ljubljana => "Slovenia",
        Tz::Europe__London => "United Kingdom",
        Tz::Europe__Luxembourg => "Luxembourg",
        Tz::Europe__Madrid => "Spain",
        Tz::Europe__Malta => "Malta",
        Tz::Europe__Mariehamn => "Finland",
        Tz::Europe__Minsk => "Belarus",
        Tz::Europe__Monaco => "Monaco",
        Tz::Europe__Moscow => "Russia",
        Tz::Europe__Nicosia => "Cyprus",
        Tz::Europe__Oslo => "Norway",
        Tz::Europe__Paris => "France",
        Tz::Europe__Podgorica => "Montenegro",
        Tz::Europe__Prague => "Czech Republic",
        Tz::Europe__Riga => "Latvia",
        Tz::Europe__Rome => "Italy",
        Tz::Europe__Samara => "Russia",
        Tz::Europe__San_Marino => "San Marino",
        Tz::Europe__Sarajevo => "Bosnia and Herzegovina",
        Tz::Europe__Saratov => "Russia",
        Tz::Europe__Simferopol => "Ukraine",
        Tz::Europe__Skopje => "North Macedonia",
        Tz::Europe__Sofia => "Bulgaria",
        Tz::Europe__Stockholm => "Sweden",
        Tz::Europe__Tallinn => "Estonia",
        Tz::Europe__Tirane => "Albania",
        Tz::Europe__Tiraspol => "Moldova",
        Tz::Europe__Ulyanovsk => "Russia",
        Tz::Europe__Uzhgorod => "Ukraine",
        Tz::Europe__Vaduz => "Liechtenstein",
        Tz::Europe__Vatican => "Vatican City",
        Tz::Europe__Vienna => "Austria",
        Tz::Europe__Vilnius => "Lithuania",
        Tz::Europe__Volgograd => "Russia",
        Tz::Europe__Warsaw => "Poland",
        Tz::Europe__Zagreb => "Croatia",
        Tz::Europe__Zaporozhye => "Ukraine",
        Tz::Europe__Zurich => "Switzerland",
        Tz::GB => "United Kingdom",
        Tz::GBEire => "United Kingdom",
        Tz::GMT => "United Kingdom",
        Tz::GMTPlus0 => "",
        Tz::GMTMinus0 => "",
        Tz::GMT0 => "",
        Tz::Greenwich => "United Kingdom",
        Tz::HST => "United States",
        Tz::Hongkong => "Hong Kong",
        Tz::Iceland => "Iceland",
        Tz::Indian__Antananarivo => "Madagascar",
        Tz::Indian__Chagos => "British Indian Ocean Territory",
        Tz::Indian__Christmas => "Christmas Island",
        Tz::Indian__Cocos => "Cocos Islands",
        Tz::Indian__Comoro => "Comoros",
        Tz::Indian__Kerguelen => "French Southern Territories",
        Tz::Indian__Mahe => "Seychelles",
        Tz::Indian__Maldives => "Maldives",
        Tz::Indian__Mauritius => "Mauritius",
        Tz::Indian__Mayotte => "Mayotte",
        Tz::Indian__Reunion => "Réunion",
        Tz::Iran => "Iran",
        Tz::Israel => "Israel",
        Tz::Jamaica => "Jamaica",
        Tz::Japan => "Japan",
        Tz::Kwajalein => "Marshall Islands",
        Tz::Libya => "Libya",
        Tz::MET => "",
        Tz::MST => "United States",
        Tz::MST7MDT => "United States",
        Tz::Mexico__BajaNorte => "Mexico",
        Tz::Mexico__BajaSur => "Mexico",
        Tz::Mexico__General => "Mexico",
        Tz::NZ => "New Zealand",
        Tz::NZCHAT => "New Zealand",
        Tz::Navajo => "United States",
        Tz::PRC => "China",
        Tz::PST8PDT => "United States",
        Tz::Pacific__Apia => "Samoa",
        Tz::Pacific__Auckland => "New Zealand",
        Tz::Pacific__Bougainville => "Papua New Guinea",
        Tz::Pacific__Chatham => "New Zealand",
        Tz::Pacific__Chuuk => "Micronesia",
        Tz::Pacific__Easter => "Chile",
        Tz::Pacific__Efate => "Vanuatu",
        Tz::Pacific__Enderbury => "Kiribati",
        Tz::Pacific__Fakaofo => "Tokelau",
        Tz::Pacific__Fiji => "Fiji",
        Tz::Pacific__Funafuti => "Tuvalu",
        Tz::Pacific__Galapagos => "Ecuador",
        Tz::Pacific__Gambier => "French Polynesia",
        Tz::Pacific__Guadalcanal => "Solomon Islands",
        Tz::Pacific__Guam => "United States",
        Tz::Pacific__Honolulu => "United States",
        Tz::Pacific__Johnston => "United States",
        Tz::Pacific__Kanton => "Kiribati",
        Tz::Pacific__Kiritimati => "Kiribati",
        Tz::Pacific__Kosrae => "Micronesia",
        Tz::Pacific__Kwajalein => "Marshall Islands",
        Tz::Pacific__Majuro => "Marshall Islands",
        Tz::Pacific__Marquesas => "French Polynesia",
        Tz::Pacific__Midway => "United States",
        Tz::Pacific__Nauru => "Nauru",
        Tz::Pacific__Niue => "Niue",
        Tz::Pacific__Norfolk => "Norfolk Island",
        Tz::Pacific__Noumea => "New Caledonia",
        Tz::Pacific__Pago_Pago => "American Samoa",
        Tz::Pacific__Palau => "Palau",
        Tz::Pacific__Pitcairn => "Pitcairn Islands",
        Tz::Pacific__Pohnpei => "Micronesia",
        Tz::Pacific__Ponape => "Micronesia",
        Tz::Pacific__Port_Moresby => "Papua New Guinea",
        Tz::Pacific__Rarotonga => "Cook Islands",
        Tz::Pacific__Saipan => "Northern Mariana Islands",
        Tz::Pacific__Samoa => "Samoa",
        Tz::Pacific__Tahiti => "French Polynesia",
        Tz::Pacific__Tarawa => "Kiribati",
        Tz::Pacific__Tongatapu => "Tonga",
        Tz::Pacific__Truk => "Micronesia",
        Tz::Pacific__Wake => "United States",
        Tz::Pacific__Wallis => "Wallis and Futuna",
        Tz::Pacific__Yap => "Micronesia",
        Tz::Poland => "Poland",
        Tz::Portugal => "Portugal",
        Tz::ROC => "Taiwan",
        Tz::ROK => "South Korea",
        Tz::Singapore => "Singapore",
        Tz::Turkey => "Turkey",
        Tz::UCT => "",
        Tz::US__Alaska => "United States",
        Tz::US__Aleutian => "United States",
        Tz::US__Arizona => "United States",
        Tz::US__Central => "United States",
        Tz::US__EastIndiana => "United States",
        Tz::US__Eastern => "United States",
        Tz::US__Hawaii => "United States",
        Tz::US__IndianaStarke => "United States",
        Tz::US__Michigan => "United States",
        Tz::US__Mountain => "United States",
        Tz::US__Pacific => "United States",
        Tz::US__Samoa => "United States",
        Tz::UTC => "",
        Tz::Universal => "",
        Tz::WSU => "Russia",
        Tz::WET => "",
        Tz::Zulu => "",
    }
    .to_string()
}

pub fn tz_to_emoji(timezone: &Tz) -> String {
    match timezone {
        Tz::Africa__Abidjan => "🇨🇮",
        Tz::Africa__Accra => "🇬🇭",
        Tz::Africa__Addis_Ababa => "🇪🇹",
        Tz::Africa__Algiers => "🇩🇿",
        Tz::Africa__Asmara => "🇪🇷",
        Tz::Africa__Asmera => "🇪🇷",
        Tz::Africa__Bamako => "🇲🇱",
        Tz::Africa__Bangui => "🇨🇫",
        Tz::Africa__Banjul => "🇬🇲",
        Tz::Africa__Bissau => "🇬🇼",
        Tz::Africa__Blantyre => "🇲🇼",
        Tz::Africa__Brazzaville => "🇨🇬",
        Tz::Africa__Bujumbura => "🇧🇮",
        Tz::Africa__Cairo => "🇪🇬",
        Tz::Africa__Casablanca => "🇲🇦",
        Tz::Africa__Ceuta => "🇪🇸",
        Tz::Africa__Conakry => "🇬🇳",
        Tz::Africa__Dakar => "🇸🇳",
        Tz::Africa__Dar_es_Salaam => "🇹🇿",
        Tz::Africa__Djibouti => "🇩🇯",
        Tz::Africa__Douala => "🇨🇲",
        Tz::Africa__El_Aaiun => "🇪🇭",
        Tz::Africa__Freetown => "🇸🇱",
        Tz::Africa__Gaborone => "🇧🇼",
        Tz::Africa__Harare => "🇿🇼",
        Tz::Africa__Johannesburg => "🇿🇦",
        Tz::Africa__Juba => "🇸🇸",
        Tz::Africa__Kampala => "🇺🇬",
        Tz::Africa__Khartoum => "🇸🇩",
        Tz::Africa__Kigali => "🇷🇼",
        Tz::Africa__Kinshasa => "🇨🇩",
        Tz::Africa__Lagos => "🇳🇬",
        Tz::Africa__Libreville => "🇬🇦",
        Tz::Africa__Lome => "🇹🇬",
        Tz::Africa__Luanda => "🇦🇴",
        Tz::Africa__Lubumbashi => "🇨🇩",
        Tz::Africa__Lusaka => "🇿🇲",
        Tz::Africa__Malabo => "🇬🇶",
        Tz::Africa__Maputo => "🇲🇿",
        Tz::Africa__Maseru => "🇱🇸",
        Tz::Africa__Mbabane => "🇸🇿",
        Tz::Africa__Mogadishu => "🇸🇴",
        Tz::Africa__Monrovia => "🇱🇷",
        Tz::Africa__Nairobi => "🇰🇪",
        Tz::Africa__Ndjamena => "🇹🇩",
        Tz::Africa__Niamey => "🇳🇪",
        Tz::Africa__Nouakchott => "🇲🇷",
        Tz::Africa__Ouagadougou => "🇧🇫",
        Tz::Africa__PortoNovo => "🇧🇯",
        Tz::Africa__Sao_Tome => "🇸🇹",
        Tz::Africa__Timbuktu => "🇲🇱",
        Tz::Africa__Tripoli => "🇱🇾",
        Tz::Africa__Tunis => "🇹🇳",
        Tz::Africa__Windhoek => "🇳🇦",
        Tz::America__Adak => "🇺🇸",
        Tz::America__Anchorage => "🇺🇸",
        Tz::America__Anguilla => "🇦🇮",
        Tz::America__Antigua => "🇦🇬",
        Tz::America__Araguaina => "🇧🇷",
        Tz::America__Argentina__Buenos_Aires => "🇦🇷",
        Tz::America__Argentina__Catamarca => "🇦🇷",
        Tz::America__Argentina__ComodRivadavia => "🇦🇷",
        Tz::America__Argentina__Cordoba => "🇦🇷",
        Tz::America__Argentina__Jujuy => "🇦🇷",
        Tz::America__Argentina__La_Rioja => "🇦🇷",
        Tz::America__Argentina__Mendoza => "🇦🇷",
        Tz::America__Argentina__Rio_Gallegos => "🇦🇷",
        Tz::America__Argentina__Salta => "🇦🇷",
        Tz::America__Argentina__San_Juan => "🇦🇷",
        Tz::America__Argentina__San_Luis => "🇦🇷",
        Tz::America__Argentina__Tucuman => "🇦🇷",
        Tz::America__Argentina__Ushuaia => "🇦🇷",
        Tz::America__Aruba => "🇦🇼",
        Tz::America__Asuncion => "🇵🇾",
        Tz::America__Atikokan => "🇨🇦",
        Tz::America__Atka => "🇺🇸",
        Tz::America__Bahia => "🇧🇷",
        Tz::America__Bahia_Banderas => "🇲🇽",
        Tz::America__Barbados => "🇧🇧",
        Tz::America__Belem => "🇧🇷",
        Tz::America__Belize => "🇧🇿",
        Tz::America__BlancSablon => "🇨🇦",
        Tz::America__Boa_Vista => "🇧🇷",
        Tz::America__Bogota => "🇨🇴",
        Tz::America__Boise => "🇺🇸",
        Tz::America__Buenos_Aires => "🇦🇷",
        Tz::America__Cambridge_Bay => "🇨🇦",
        Tz::America__Campo_Grande => "🇧🇷",
        Tz::America__Cancun => "🇲🇽",
        Tz::America__Caracas => "🇻🇪",
        Tz::America__Catamarca => "🇦🇷",
        Tz::America__Cayenne => "🇬🇫",
        Tz::America__Cayman => "🇰🇾",
        Tz::America__Chicago => "🇺🇸",
        Tz::America__Chihuahua => "🇲🇽",
        Tz::America__Ciudad_Juarez => "🇲🇽",
        Tz::America__Coral_Harbour => "🇨🇦",
        Tz::America__Cordoba => "🇦🇷",
        Tz::America__Costa_Rica => "🇨🇷",
        Tz::America__Coyhaique => "🇨🇱",
        Tz::America__Creston => "🇨🇦",
        Tz::America__Cuiaba => "🇧🇷",
        Tz::America__Curacao => "🇨🇼",
        Tz::America__Danmarkshavn => "🇬🇱",
        Tz::America__Dawson => "🇨🇦",
        Tz::America__Dawson_Creek => "🇨🇦",
        Tz::America__Denver => "🇺🇸",
        Tz::America__Detroit => "🇺🇸",
        Tz::America__Dominica => "🇩🇲",
        Tz::America__Edmonton => "🇨🇦",
        Tz::America__Eirunepe => "🇧🇷",
        Tz::America__El_Salvador => "🇸🇻",
        Tz::America__Ensenada => "🇲🇽",
        Tz::America__Fort_Nelson => "🇨🇦",
        Tz::America__Fort_Wayne => "🇺🇸",
        Tz::America__Fortaleza => "🇧🇷",
        Tz::America__Glace_Bay => "🇨🇦",
        Tz::America__Godthab => "🇬🇱",
        Tz::America__Goose_Bay => "🇨🇦",
        Tz::America__Grand_Turk => "🇹🇨",
        Tz::America__Grenada => "🇬🇩",
        Tz::America__Guadeloupe => "🇬🇵",
        Tz::America__Guatemala => "🇬🇹",
        Tz::America__Guayaquil => "🇪🇨",
        Tz::America__Guyana => "🇬🇾",
        Tz::America__Halifax => "🇨🇦",
        Tz::America__Havana => "🇨🇺",
        Tz::America__Hermosillo => "🇲🇽",
        Tz::America__Indiana__Indianapolis => "🇺🇸",
        Tz::America__Indiana__Knox => "🇺🇸",
        Tz::America__Indiana__Marengo => "🇺🇸",
        Tz::America__Indiana__Petersburg => "🇺🇸",
        Tz::America__Indiana__Tell_City => "🇺🇸",
        Tz::America__Indiana__Vevay => "🇺🇸",
        Tz::America__Indiana__Vincennes => "🇺🇸",
        Tz::America__Indiana__Winamac => "🇺🇸",
        Tz::America__Indianapolis => "🇺🇸",
        Tz::America__Inuvik => "🇨🇦",
        Tz::America__Iqaluit => "🇨🇦",
        Tz::America__Jamaica => "🇯🇲",
        Tz::America__Jujuy => "🇦🇷",
        Tz::America__Juneau => "🇺🇸",
        Tz::America__Kentucky__Louisville => "🇺🇸",
        Tz::America__Kentucky__Monticello => "🇺🇸",
        Tz::America__Knox_IN => "🇺🇸",
        Tz::America__Kralendijk => "🇧🇶",
        Tz::America__La_Paz => "🇧🇴",
        Tz::America__Lima => "🇵🇪",
        Tz::America__Los_Angeles => "🇺🇸",
        Tz::America__Louisville => "🇺🇸",
        Tz::America__Lower_Princes => "🇸🇽",
        Tz::America__Maceio => "🇧🇷",
        Tz::America__Managua => "🇳🇮",
        Tz::America__Manaus => "🇧🇷",
        Tz::America__Marigot => "🇲🇫",
        Tz::America__Martinique => "🇲🇶",
        Tz::America__Matamoros => "🇲🇽",
        Tz::America__Mazatlan => "🇲🇽",
        Tz::America__Mendoza => "🇦🇷",
        Tz::America__Menominee => "🇺🇸",
        Tz::America__Merida => "🇲🇽",
        Tz::America__Metlakatla => "🇺🇸",
        Tz::America__Mexico_City => "🇲🇽",
        Tz::America__Miquelon => "🇵🇲",
        Tz::America__Moncton => "🇨🇦",
        Tz::America__Monterrey => "🇲🇽",
        Tz::America__Montevideo => "🇺🇾",
        Tz::America__Montreal => "🇨🇦",
        Tz::America__Montserrat => "🇲🇸",
        Tz::America__Nassau => "🇧🇸",
        Tz::America__New_York => "🇺🇸",
        Tz::America__Nipigon => "🇨🇦",
        Tz::America__Nome => "🇺🇸",
        Tz::America__Noronha => "🇧🇷",
        Tz::America__North_Dakota__Beulah => "🇺🇸",
        Tz::America__North_Dakota__Center => "🇺🇸",
        Tz::America__North_Dakota__New_Salem => "🇺🇸",
        Tz::America__Nuuk => "🇬🇱",
        Tz::America__Ojinaga => "🇲🇽",
        Tz::America__Panama => "🇵🇦",
        Tz::America__Pangnirtung => "🇨🇦",
        Tz::America__Paramaribo => "🇸🇷",
        Tz::America__Phoenix => "🇺🇸",
        Tz::America__PortauPrince => "🇭🇹",
        Tz::America__Port_of_Spain => "🇹🇹",
        Tz::America__Porto_Acre => "🇧🇷",
        Tz::America__Porto_Velho => "🇧🇷",
        Tz::America__Puerto_Rico => "🇵🇷",
        Tz::America__Punta_Arenas => "🇨🇱",
        Tz::America__Rainy_River => "🇨🇦",
        Tz::America__Rankin_Inlet => "🇨🇦",
        Tz::America__Recife => "🇧🇷",
        Tz::America__Regina => "🇨🇦",
        Tz::America__Resolute => "🇨🇦",
        Tz::America__Rio_Branco => "🇧🇷",
        Tz::America__Rosario => "🇦🇷",
        Tz::America__Santa_Isabel => "🇲🇽",
        Tz::America__Santarem => "🇧🇷",
        Tz::America__Santiago => "🇨🇱",
        Tz::America__Santo_Domingo => "🇩🇴",
        Tz::America__Sao_Paulo => "🇧🇷",
        Tz::America__Scoresbysund => "🇬🇱",
        Tz::America__Shiprock => "🇺🇸",
        Tz::America__Sitka => "🇺🇸",
        Tz::America__St_Barthelemy => "🇧🇱",
        Tz::America__St_Johns => "🇨🇦",
        Tz::America__St_Kitts => "🇰🇳",
        Tz::America__St_Lucia => "🇱🇨",
        Tz::America__St_Thomas => "🇻🇮",
        Tz::America__St_Vincent => "🇻🇨",
        Tz::America__Swift_Current => "🇨🇦",
        Tz::America__Tegucigalpa => "🇭🇳",
        Tz::America__Thule => "🇬🇱",
        Tz::America__Thunder_Bay => "🇨🇦",
        Tz::America__Tijuana => "🇲🇽",
        Tz::America__Toronto => "🇨🇦",
        Tz::America__Tortola => "🇻🇬",
        Tz::America__Vancouver => "🇨🇦",
        Tz::America__Virgin => "🇻🇮",
        Tz::America__Whitehorse => "🇨🇦",
        Tz::America__Winnipeg => "🇨🇦",
        Tz::America__Yakutat => "🇺🇸",
        Tz::America__Yellowknife => "🇨🇦",
        Tz::Antarctica__Casey => "🇦🇶",
        Tz::Antarctica__Davis => "🇦🇶",
        Tz::Antarctica__DumontDUrville => "🇦🇶",
        Tz::Antarctica__Macquarie => "🇦🇶",
        Tz::Antarctica__Mawson => "🇦🇶",
        Tz::Antarctica__McMurdo => "🇦🇶",
        Tz::Antarctica__Palmer => "🇦🇶",
        Tz::Antarctica__Rothera => "🇦🇶",
        Tz::Antarctica__South_Pole => "🇦🇶",
        Tz::Antarctica__Syowa => "🇦🇶",
        Tz::Antarctica__Troll => "🇦🇶",
        Tz::Antarctica__Vostok => "🇦🇶",
        Tz::Arctic__Longyearbyen => "🇸🇯",
        Tz::Asia__Aden => "🇾🇪",
        Tz::Asia__Almaty => "🇰🇿",
        Tz::Asia__Amman => "🇯🇴",
        Tz::Asia__Anadyr => "🇷🇺",
        Tz::Asia__Aqtau => "🇰🇿",
        Tz::Asia__Aqtobe => "🇰🇿",
        Tz::Asia__Ashgabat => "🇹🇲",
        Tz::Asia__Ashkhabad => "🇹🇲",
        Tz::Asia__Atyrau => "🇰🇿",
        Tz::Asia__Baghdad => "🇮🇶",
        Tz::Asia__Bahrain => "🇧🇭",
        Tz::Asia__Baku => "🇦🇿",
        Tz::Asia__Bangkok => "🇹🇭",
        Tz::Asia__Barnaul => "🇷🇺",
        Tz::Asia__Beirut => "🇱🇧",
        Tz::Asia__Bishkek => "🇰🇬",
        Tz::Asia__Brunei => "🇧🇳",
        Tz::Asia__Calcutta => "🇮🇳",
        Tz::Asia__Chita => "🇷🇺",
        Tz::Asia__Choibalsan => "🇲🇳",
        Tz::Asia__Chongqing => "🇨🇳",
        Tz::Asia__Chungking => "🇨🇳",
        Tz::Asia__Colombo => "🇱🇰",
        Tz::Asia__Dacca => "🇧🇩",
        Tz::Asia__Damascus => "🇸🇾",
        Tz::Asia__Dhaka => "🇧🇩",
        Tz::Asia__Dili => "🇹🇱",
        Tz::Asia__Dubai => "🇦🇪",
        Tz::Asia__Dushanbe => "🇹🇯",
        Tz::Asia__Famagusta => "🇨🇾",
        Tz::Asia__Gaza => "🇵🇸",
        Tz::Asia__Harbin => "🇨🇳",
        Tz::Asia__Hebron => "🇵🇸",
        Tz::Asia__Ho_Chi_Minh => "🇻🇳",
        Tz::Asia__Hong_Kong => "🇭🇰",
        Tz::Asia__Hovd => "🇲🇳",
        Tz::Asia__Irkutsk => "🇷🇺",
        Tz::Asia__Istanbul => "🇹🇷",
        Tz::Asia__Jakarta => "🇮🇩",
        Tz::Asia__Jayapura => "🇮🇩",
        Tz::Asia__Jerusalem => "🇮🇱",
        Tz::Asia__Kabul => "🇦🇫",
        Tz::Asia__Kamchatka => "🇷🇺",
        Tz::Asia__Karachi => "🇵🇰",
        Tz::Asia__Kashgar => "🇨🇳",
        Tz::Asia__Kathmandu => "🇳🇵",
        Tz::Asia__Katmandu => "🇳🇵",
        Tz::Asia__Khandyga => "🇷🇺",
        Tz::Asia__Kolkata => "🇮🇳",
        Tz::Asia__Krasnoyarsk => "🇷🇺",
        Tz::Asia__Kuala_Lumpur => "🇲🇾",
        Tz::Asia__Kuching => "🇲🇾",
        Tz::Asia__Kuwait => "🇰🇼",
        Tz::Asia__Macao => "🇲🇴",
        Tz::Asia__Macau => "🇲🇴",
        Tz::Asia__Magadan => "🇷🇺",
        Tz::Asia__Makassar => "🇮🇩",
        Tz::Asia__Manila => "🇵🇭",
        Tz::Asia__Muscat => "🇴🇲",
        Tz::Asia__Nicosia => "🇨🇾",
        Tz::Asia__Novokuznetsk => "🇷🇺",
        Tz::Asia__Novosibirsk => "🇷🇺",
        Tz::Asia__Omsk => "🇷🇺",
        Tz::Asia__Oral => "🇰🇿",
        Tz::Asia__Phnom_Penh => "🇰🇭",
        Tz::Asia__Pontianak => "🇮🇩",
        Tz::Asia__Pyongyang => "🇰🇵",
        Tz::Asia__Qatar => "🇶🇦",
        Tz::Asia__Qostanay => "🇰🇿",
        Tz::Asia__Qyzylorda => "🇰🇿",
        Tz::Asia__Rangoon => "🇲🇲",
        Tz::Asia__Riyadh => "🇸🇦",
        Tz::Asia__Saigon => "🇻🇳",
        Tz::Asia__Sakhalin => "🇷🇺",
        Tz::Asia__Samarkand => "🇺🇿",
        Tz::Asia__Seoul => "🇰🇷",
        Tz::Asia__Shanghai => "🇨🇳",
        Tz::Asia__Singapore => "🇸🇬",
        Tz::Asia__Srednekolymsk => "🇷🇺",
        Tz::Asia__Taipei => "🇹🇼",
        Tz::Asia__Tashkent => "🇺🇿",
        Tz::Asia__Tbilisi => "🇬🇪",
        Tz::Asia__Tehran => "🇮🇷",
        Tz::Asia__Tel_Aviv => "🇮🇱",
        Tz::Asia__Thimbu => "🇧🇹",
        Tz::Asia__Thimphu => "🇧🇹",
        Tz::Asia__Tokyo => "🇯🇵",
        Tz::Asia__Tomsk => "🇷🇺",
        Tz::Asia__Ujung_Pandang => "🇮🇩",
        Tz::Asia__Ulaanbaatar => "🇲🇳",
        Tz::Asia__Ulan_Bator => "🇲🇳",
        Tz::Asia__Urumqi => "🇨🇳",
        Tz::Asia__UstNera => "🇷🇺",
        Tz::Asia__Vientiane => "🇱🇦",
        Tz::Asia__Vladivostok => "🇷🇺",
        Tz::Asia__Yakutsk => "🇷🇺",
        Tz::Asia__Yangon => "🇲🇲",
        Tz::Asia__Yekaterinburg => "🇷🇺",
        Tz::Asia__Yerevan => "🇦🇲",
        Tz::Atlantic__Azores => "🇵🇹",
        Tz::Atlantic__Bermuda => "🇧🇲",
        Tz::Atlantic__Canary => "🇪🇸",
        Tz::Atlantic__Cape_Verde => "🇨🇻",
        Tz::Atlantic__Faeroe => "🇫🇴",
        Tz::Atlantic__Faroe => "🇫🇴",
        Tz::Atlantic__Jan_Mayen => "🇳🇴",
        Tz::Atlantic__Madeira => "🇵🇹",
        Tz::Atlantic__Reykjavik => "🇮🇸",
        Tz::Atlantic__South_Georgia => "🇬🇸",
        Tz::Atlantic__St_Helena => "🇸🇭",
        Tz::Atlantic__Stanley => "🇫🇰",
        Tz::Australia__ACT => "🇦🇺",
        Tz::Australia__Adelaide => "🇦🇺",
        Tz::Australia__Brisbane => "🇦🇺",
        Tz::Australia__Broken_Hill => "🇦🇺",
        Tz::Australia__Canberra => "🇦🇺",
        Tz::Australia__Currie => "🇦🇺",
        Tz::Australia__Darwin => "🇦🇺",
        Tz::Australia__Eucla => "🇦🇺",
        Tz::Australia__Hobart => "🇦🇺",
        Tz::Australia__LHI => "🇦🇺",
        Tz::Australia__Lindeman => "🇦🇺",
        Tz::Australia__Lord_Howe => "🇦🇺",
        Tz::Australia__Melbourne => "🇦🇺",
        Tz::Australia__NSW => "🇦🇺",
        Tz::Australia__North => "🇦🇺",
        Tz::Australia__Perth => "🇦🇺",
        Tz::Australia__Queensland => "🇦🇺",
        Tz::Australia__South => "🇦🇺",
        Tz::Australia__Sydney => "🇦🇺",
        Tz::Australia__Tasmania => "🇦🇺",
        Tz::Australia__Victoria => "🇦🇺",
        Tz::Australia__West => "🇦🇺",
        Tz::Australia__Yancowinna => "🇦🇺",
        Tz::Brazil__Acre => "🇧🇷",
        Tz::Brazil__DeNoronha => "🇧🇷",
        Tz::Brazil__East => "🇧🇷",
        Tz::Brazil__West => "🇧🇷",
        Tz::CET => "",
        Tz::CST6CDT => "",
        Tz::Canada__Atlantic => "🇨🇦",
        Tz::Canada__Central => "🇨🇦",
        Tz::Canada__Eastern => "🇨🇦",
        Tz::Canada__Mountain => "🇨🇦",
        Tz::Canada__Newfoundland => "🇨🇦",
        Tz::Canada__Pacific => "🇨🇦",
        Tz::Canada__Saskatchewan => "🇨🇦",
        Tz::Canada__Yukon => "🇨🇦",
        Tz::Chile__Continental => "🇨🇱",
        Tz::Chile__EasterIsland => "🇨🇱",
        Tz::Cuba => "🇨🇺",
        Tz::EET => "",
        Tz::EST => "",
        Tz::EST5EDT => "",
        Tz::Egypt => "🇪🇬",
        Tz::Eire => "🇮🇪",
        Tz::Etc__GMT => "",
        Tz::Etc__GMTPlus0 => "",
        Tz::Etc__GMTPlus1 => "",
        Tz::Etc__GMTPlus10 => "",
        Tz::Etc__GMTPlus11 => "",
        Tz::Etc__GMTPlus12 => "",
        Tz::Etc__GMTPlus2 => "",
        Tz::Etc__GMTPlus3 => "",
        Tz::Etc__GMTPlus4 => "",
        Tz::Etc__GMTPlus5 => "",
        Tz::Etc__GMTPlus6 => "",
        Tz::Etc__GMTPlus7 => "",
        Tz::Etc__GMTPlus8 => "",
        Tz::Etc__GMTPlus9 => "",
        Tz::Etc__GMTMinus0 => "",
        Tz::Etc__GMTMinus1 => "",
        Tz::Etc__GMTMinus10 => "",
        Tz::Etc__GMTMinus11 => "",
        Tz::Etc__GMTMinus12 => "",
        Tz::Etc__GMTMinus13 => "",
        Tz::Etc__GMTMinus14 => "",
        Tz::Etc__GMTMinus2 => "",
        Tz::Etc__GMTMinus3 => "",
        Tz::Etc__GMTMinus4 => "",
        Tz::Etc__GMTMinus5 => "",
        Tz::Etc__GMTMinus6 => "",
        Tz::Etc__GMTMinus7 => "",
        Tz::Etc__GMTMinus8 => "",
        Tz::Etc__GMTMinus9 => "",
        Tz::Etc__GMT0 => "",
        Tz::Etc__Greenwich => "🇬🇧",
        Tz::Etc__UCT => "",
        Tz::Etc__UTC => "",
        Tz::Etc__Universal => "",
        Tz::Etc__Zulu => "",
        Tz::Europe__Amsterdam => "🇳🇱",
        Tz::Europe__Andorra => "🇦🇩",
        Tz::Europe__Astrakhan => "🇷🇺",
        Tz::Europe__Athens => "🇬🇷",
        Tz::Europe__Belfast => "🇬🇧",
        Tz::Europe__Belgrade => "🇷🇸",
        Tz::Europe__Berlin => "🇩🇪",
        Tz::Europe__Bratislava => "🇸🇰",
        Tz::Europe__Brussels => "🇧🇪",
        Tz::Europe__Bucharest => "🇷🇴",
        Tz::Europe__Budapest => "🇭🇺",
        Tz::Europe__Busingen => "🇩🇪",
        Tz::Europe__Chisinau => "🇲🇩",
        Tz::Europe__Copenhagen => "🇩🇰",
        Tz::Europe__Dublin => "🇮🇪",
        Tz::Europe__Gibraltar => "🇬🇮",
        Tz::Europe__Guernsey => "🇬🇬",
        Tz::Europe__Helsinki => "🇫🇮",
        Tz::Europe__Isle_of_Man => "🇮🇲",
        Tz::Europe__Istanbul => "🇹🇷",
        Tz::Europe__Jersey => "🇯🇪",
        Tz::Europe__Kaliningrad => "🇷🇺",
        Tz::Europe__Kiev => "🇺🇦",
        Tz::Europe__Kirov => "🇷🇺",
        Tz::Europe__Kyiv => "🇺🇦",
        Tz::Europe__Lisbon => "🇵🇹",
        Tz::Europe__Ljubljana => "🇸🇮",
        Tz::Europe__London => "🇬🇧",
        Tz::Europe__Luxembourg => "🇱🇺",
        Tz::Europe__Madrid => "🇪🇸",
        Tz::Europe__Malta => "🇲🇹",
        Tz::Europe__Mariehamn => "🇦🇽",
        Tz::Europe__Minsk => "🇧🇾",
        Tz::Europe__Monaco => "🇲🇨",
        Tz::Europe__Moscow => "🇷🇺",
        Tz::Europe__Nicosia => "🇨🇾",
        Tz::Europe__Oslo => "🇳🇴",
        Tz::Europe__Paris => "🇫🇷",
        Tz::Europe__Podgorica => "🇲🇪",
        Tz::Europe__Prague => "🇨🇿",
        Tz::Europe__Riga => "🇱🇻",
        Tz::Europe__Rome => "🇮🇹",
        Tz::Europe__Samara => "🇷🇺",
        Tz::Europe__San_Marino => "🇸🇲",
        Tz::Europe__Sarajevo => "🇧🇦",
        Tz::Europe__Saratov => "🇷🇺",
        Tz::Europe__Simferopol => "🇺🇦",
        Tz::Europe__Skopje => "🇲🇰",
        Tz::Europe__Sofia => "🇧🇬",
        Tz::Europe__Stockholm => "🇸🇪",
        Tz::Europe__Tallinn => "🇪🇪",
        Tz::Europe__Tirane => "🇦🇱",
        Tz::Europe__Tiraspol => "🇲🇩",
        Tz::Europe__Ulyanovsk => "🇷🇺",
        Tz::Europe__Uzhgorod => "🇺🇦",
        Tz::Europe__Vaduz => "🇱🇮",
        Tz::Europe__Vatican => "🇻🇦",
        Tz::Europe__Vienna => "🇦🇹",
        Tz::Europe__Vilnius => "🇱🇹",
        Tz::Europe__Volgograd => "🇷🇺",
        Tz::Europe__Warsaw => "🇵🇱",
        Tz::Europe__Zagreb => "🇭🇷",
        Tz::Europe__Zaporozhye => "🇺🇦",
        Tz::Europe__Zurich => "🇨🇭",
        Tz::GB => "🇬🇧",
        Tz::GBEire => "🇬🇧",
        Tz::GMT => "🇬🇧",
        Tz::GMTPlus0 => "🇬🇧",
        Tz::GMTMinus0 => "🇬🇧",
        Tz::GMT0 => "🇬🇧",
        Tz::Greenwich => "🇬🇧",
        Tz::HST => "",
        Tz::Hongkong => "🇭🇰",
        Tz::Iceland => "🇮🇸",
        Tz::Indian__Antananarivo => "🇲🇬",
        Tz::Indian__Chagos => "🇮🇴",
        Tz::Indian__Christmas => "🇨🇽",
        Tz::Indian__Cocos => "🇨🇨",
        Tz::Indian__Comoro => "🇰🇲",
        Tz::Indian__Kerguelen => "🇹🇫",
        Tz::Indian__Mahe => "🇸🇨",
        Tz::Indian__Maldives => "🇲🇻",
        Tz::Indian__Mauritius => "🇲🇺",
        Tz::Indian__Mayotte => "🇾🇹",
        Tz::Indian__Reunion => "🇷🇪",
        Tz::Iran => "🇮🇷",
        Tz::Israel => "🇮🇱",
        Tz::Jamaica => "🇯🇲",
        Tz::Japan => "🇯🇵",
        Tz::Kwajalein => "🇲🇭",
        Tz::Libya => "🇱🇾",
        Tz::MET => "",
        Tz::MST => "",
        Tz::MST7MDT => "",
        Tz::Mexico__BajaNorte => "🇲🇽",
        Tz::Mexico__BajaSur => "🇲🇽",
        Tz::Mexico__General => "🇲🇽",
        Tz::NZ => "",
        Tz::NZCHAT => "",
        Tz::Navajo => "",
        Tz::PRC => "",
        Tz::PST8PDT => "",
        Tz::Pacific__Apia => "🇼🇸",
        Tz::Pacific__Auckland => "🇳🇿",
        Tz::Pacific__Bougainville => "🇵🇬",
        Tz::Pacific__Chatham => "🇳🇿",
        Tz::Pacific__Chuuk => "🇫🇲",
        Tz::Pacific__Easter => "🇨🇱",
        Tz::Pacific__Efate => "🇻🇺",
        Tz::Pacific__Enderbury => "🇰🇮",
        Tz::Pacific__Fakaofo => "🇹🇰",
        Tz::Pacific__Fiji => "🇫🇯",
        Tz::Pacific__Funafuti => "🇹🇻",
        Tz::Pacific__Galapagos => "🇪🇨",
        Tz::Pacific__Gambier => "🇵🇫",
        Tz::Pacific__Guadalcanal => "🇸🇧",
        Tz::Pacific__Guam => "🇬🇺",
        Tz::Pacific__Honolulu => "🇺🇸",
        Tz::Pacific__Johnston => "🇺🇲",
        Tz::Pacific__Kanton => "🇰🇮",
        Tz::Pacific__Kiritimati => "🇰🇮",
        Tz::Pacific__Kosrae => "🇫🇲",
        Tz::Pacific__Kwajalein => "🇲🇭",
        Tz::Pacific__Majuro => "🇲🇭",
        Tz::Pacific__Marquesas => "🇵🇫",
        Tz::Pacific__Midway => "🇺🇲",
        Tz::Pacific__Nauru => "🇳🇷",
        Tz::Pacific__Niue => "🇳🇺",
        Tz::Pacific__Norfolk => "🇳🇫",
        Tz::Pacific__Noumea => "🇳🇨",
        Tz::Pacific__Pago_Pago => "🇦🇸",
        Tz::Pacific__Palau => "🇵🇼",
        Tz::Pacific__Pitcairn => "🇵🇳",
        Tz::Pacific__Pohnpei => "🇫🇲",
        Tz::Pacific__Ponape => "🇫🇲",
        Tz::Pacific__Port_Moresby => "🇵🇬",
        Tz::Pacific__Rarotonga => "🇨🇰",
        Tz::Pacific__Saipan => "🇲🇵",
        Tz::Pacific__Samoa => "🇼🇸",
        Tz::Pacific__Tahiti => "🇵🇫",
        Tz::Pacific__Tarawa => "🇰🇮",
        Tz::Pacific__Tongatapu => "🇹🇴",
        Tz::Pacific__Truk => "🇫🇲",
        Tz::Pacific__Wake => "🇺🇲",
        Tz::Pacific__Wallis => "🇼🇫",
        Tz::Pacific__Yap => "🇫🇲",
        Tz::Poland => "🇵🇱",
        Tz::Portugal => "🇵🇹",
        Tz::ROC => "",
        Tz::ROK => "",
        Tz::Singapore => "🇸🇬",
        Tz::Turkey => "🇹🇷",
        Tz::UCT => "",
        Tz::US__Alaska => "🇺🇸",
        Tz::US__Aleutian => "🇺🇸",
        Tz::US__Arizona => "🇺🇸",
        Tz::US__Central => "🇺🇸",
        Tz::US__EastIndiana => "🇺🇸",
        Tz::US__Eastern => "🇺🇸",
        Tz::US__Hawaii => "🇺🇸",
        Tz::US__IndianaStarke => "🇺🇸",
        Tz::US__Michigan => "🇺🇸",
        Tz::US__Mountain => "🇺🇸",
        Tz::US__Pacific => "🇺🇸",
        Tz::US__Samoa => "🇺🇸",
        Tz::UTC => "",
        Tz::Universal => "",
        Tz::WSU => "",
        Tz::WET => "",
        Tz::Zulu => "",
    }
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_timezones_can_be_sorted() {
        let mut timezones = vec![
            TimeIncrement::now(Tz::Europe__Paris),
            TimeIncrement::now(Tz::Europe__London),
        ];

        timezones.sort();

        assert_eq!(
            timezones,
            vec![
                TimeIncrement::now(Tz::Europe__London),
                TimeIncrement::now(Tz::Europe__Paris)
            ]
        );
    }
}
